package com.sysh.mapper;

import com.sysh.entity.AK11AC08DD;
import com.sysh.entity.AK11DD;

import java.util.List;
import java.util.Map;

public interface AK11DDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AK11
     *
     * @mbg.generated
     */
    int insert(AK11DD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AK11
     *
     * @mbg.generated
     */
    int insertSelective(AK11DD record);

    AK11DD findAk11DD(String helpNumber);

    String findAk11Name(String helpNumber);

    List<AK11DD> findFour(String helpNumber);

    Integer updateHelpDetail(AK11DD ak11DD);

    //帮扶责任人的信息展示带有时间的修改
    AK11AC08DD findAk11Ac08(Map<String, String> map);






}