package com.sysh.mapper;

import com.sysh.entity.helpmea.BottomDisabledDD;

import java.util.List;

public interface BottomDisabledDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    int insert(BottomDisabledDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    int insertSelective(BottomDisabledDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    BottomDisabledDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BottomDisabledDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BottomDisabledDD record);

    BottomDisabledDD findBottomDisabledByid(String idNumber);
    BottomDisabledDD findBottomDisabledByid1(String idNumber);


}