package com.sysh.mapper;

import com.sysh.entity.helpmea.BottomGuaranteeCivilDD;

import java.util.List;

public interface BottomGuaranteeCivilDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    int insert(BottomGuaranteeCivilDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    int insertSelective(BottomGuaranteeCivilDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    BottomGuaranteeCivilDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BottomGuaranteeCivilDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BottomGuaranteeCivilDD record);

    List<BottomGuaranteeCivilDD> findBottomCivil(String idNumberPoverty);

    BottomGuaranteeCivilDD findBottomCivilByIdNumber(String idNumber);
    BottomGuaranteeCivilDD findBottomCivilByIdNumber1(String idNumber);
}