package com.sysh.mapper;

import com.sysh.entity.helpmea.EcologicalPovertyDD;

public interface EcologicalPovertyDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    int insert(EcologicalPovertyDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    int insertSelective(EcologicalPovertyDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    EcologicalPovertyDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EcologicalPovertyDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcologicalPovertyDD record);

    EcologicalPovertyDD findEcologicalPovertyByID(String idNumber);
    EcologicalPovertyDD findEcologicalPovertyByID1(String idNumber);
}