package com.sysh.mapper;

import com.sysh.entity.helpmea.EducationDD;

public interface EducationDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    int insert(EducationDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    int insertSelective(EducationDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    EducationDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EducationDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EducationDD record);

    EducationDD findEducationByid(String idNumber);
    EducationDD findEducationByid1(String idNumber);
}