package com.sysh.mapper;

import com.sysh.entity.helpmea.EmploymentDD;

public interface EmploymentDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    int insert(EmploymentDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    int insertSelective(EmploymentDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    EmploymentDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmploymentDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmploymentDD record);

    EmploymentDD findEmployByIdNumber(String IdNumber);
    EmploymentDD findEmployByIdNumber1(String IdNumber);
}