package com.sysh.mapper;

import com.sysh.entity.helpmea.FinanceDD;

public interface FinanceDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_FINANCE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_FINANCE
     *
     * @mbg.generated
     */
    int insert(FinanceDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_FINANCE
     *
     * @mbg.generated
     */
    int insertSelective(FinanceDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_FINANCE
     *
     * @mbg.generated
     */
    FinanceDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_FINANCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FinanceDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_FINANCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FinanceDD record);

    FinanceDD findFinanceByid(String name);
    FinanceDD findFinanceByid1(String name);
}