package com.sysh.mapper;

import com.sysh.entity.helpmea.HealthDD;

public interface HealthDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_HEALTH
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_HEALTH
     *
     * @mbg.generated
     */
    int insert(HealthDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_HEALTH
     *
     * @mbg.generated
     */
    int insertSelective(HealthDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_HEALTH
     *
     * @mbg.generated
     */
    HealthDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_HEALTH
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HealthDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_HEALTH
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HealthDD record);

    HealthDD findHealthByid(String idNumber);
    HealthDD findHealthByid1(String idNumber);
}