package com.sysh.mapper;

import com.sysh.entity.helpmea.IdstProjwayDD;

public interface IdstProjwayDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IDST_PROJWAY
     *
     * @mbg.generated
     */
    int insert(IdstProjwayDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IDST_PROJWAY
     *
     * @mbg.generated
     */
    int insertSelective(IdstProjwayDD record);

    //产业扶贫具体内容
    IdstProjwayDD findIdstProjwayByidNumber(String idNumber);
    IdstProjwayDD findIdstProjwayByidNumber1(String idNumber);
}