package com.sysh.mapper;

import com.sysh.entity.helpmea.ImmigrantRelocationDD;

public interface ImmigrantRelocationDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IMMIGRANT_RELOCATION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IMMIGRANT_RELOCATION
     *
     * @mbg.generated
     */
    int insert(ImmigrantRelocationDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IMMIGRANT_RELOCATION
     *
     * @mbg.generated
     */
    int insertSelective(ImmigrantRelocationDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IMMIGRANT_RELOCATION
     *
     * @mbg.generated
     */
    ImmigrantRelocationDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IMMIGRANT_RELOCATION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ImmigrantRelocationDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IMMIGRANT_RELOCATION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ImmigrantRelocationDD record);

    ImmigrantRelocationDD findImmRelocationByID(String idNumber);
    ImmigrantRelocationDD findImmRelocationByID1(String idNumber);


}