package com.sysh.mapper;

import com.sysh.entity.MeasureFieldDD;

import java.util.List;

public interface MeasureFieldDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    int insert(MeasureFieldDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    int insertSelective(MeasureFieldDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    MeasureFieldDD selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MeasureFieldDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MeasureFieldDD record);

    List<MeasureFieldDD> findMeassureField(String tableName);
}