package com.sysh.mapper;

import com.sysh.entity.helpmea.ReconstDangerDD;

public interface ReconstDangerDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    int insert(ReconstDangerDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    int insertSelective(ReconstDangerDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    ReconstDangerDD selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReconstDangerDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReconstDangerDD record);

    ReconstDangerDD findReconstDangerByID(String idNumber);
    ReconstDangerDD findReconstDangerByID1(String idNumber);

}