package com.sysh.mapper;

import com.sysh.entity.Time1;

import java.util.Map;

public interface TimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_time
     *
     * @mbg.generated
     */
    int insert(Time1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_time
     *
     * @mbg.generated
     */
    int insertSelective(Time1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_time
     *
     * @mbg.generated
     */
    Time1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Time1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Time1 record);

    Time1 select(Map<String, Object> map);
}