package com.sysh.mapper;

import com.sysh.entity.helpmea.VillInfrastDD;

import java.util.Map;

public interface VillInfrastDDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_VILL_INFRAST
     *
     * @mbg.generated
     */
    int insert(VillInfrastDD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_VILL_INFRAST
     *
     * @mbg.generated
     */
    int insertSelective(VillInfrastDD record);

    VillInfrastDD findByHelpNumber(Map<String, String> map);
}