package com.sysh.entity.helpmea;

import java.io.Serializable;
import java.math.BigDecimal;

public class BottomGuaranteeCivilDD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.DISTRICT_NAME
     *
     * @mbg.generated
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.TOWN_NAME
     *
     * @mbg.generated
     */
    private String townName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.VILLAGE_NAME
     *
     * @mbg.generated
     */
    private String villageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.POVERTY_NAME
     *
     * @mbg.generated
     */
    private String povertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER_POVERTY
     *
     * @mbg.generated
     */
    private String idNumberPoverty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.IS_FIVE_INSURED
     *
     * @mbg.generated
     */
    private String isFiveInsured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.FEEDING_MODE
     *
     * @mbg.generated
     */
    private String feedingMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.FIVE_PREMIUMS
     *
     * @mbg.generated
     */
    private BigDecimal fivePremiums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.IS_LOW_INSURED
     *
     * @mbg.generated
     */
    private String isLowInsured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.NAME_OF_MEMBER
     *
     * @mbg.generated
     */
    private String nameOfMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.SEX
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.RELATION_POVERTY
     *
     * @mbg.generated
     */
    private String relationPoverty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER
     *
     * @mbg.generated
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_THE_POPULATION
     *
     * @mbg.generated
     */
    private Long protectThePopulation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_TYPE
     *
     * @mbg.generated
     */
    private String protectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.CLASSIFICATION_HEDGE
     *
     * @mbg.generated
     */
    private BigDecimal classificationHedge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.LOW_PREMIUM
     *
     * @mbg.generated
     */
    private BigDecimal lowPremium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_GUARANTEE_CIVIL.ZONE_YEAR
     *
     * @mbg.generated
     */
    private Long zoneYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID
     *
     * @param id the value for TBL_BOTTOM_GUARANTEE_CIVIL.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.DISTRICT_NAME
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.DISTRICT_NAME
     *
     * @param districtName the value for TBL_BOTTOM_GUARANTEE_CIVIL.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.TOWN_NAME
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.TOWN_NAME
     *
     * @mbg.generated
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.TOWN_NAME
     *
     * @param townName the value for TBL_BOTTOM_GUARANTEE_CIVIL.TOWN_NAME
     *
     * @mbg.generated
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.VILLAGE_NAME
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.VILLAGE_NAME
     *
     * @param villageName the value for TBL_BOTTOM_GUARANTEE_CIVIL.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public void setVillageName(String villageName) {
        this.villageName = villageName == null ? null : villageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.POVERTY_NAME
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.POVERTY_NAME
     *
     * @mbg.generated
     */
    public String getPovertyName() {
        return povertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.POVERTY_NAME
     *
     * @param povertyName the value for TBL_BOTTOM_GUARANTEE_CIVIL.POVERTY_NAME
     *
     * @mbg.generated
     */
    public void setPovertyName(String povertyName) {
        this.povertyName = povertyName == null ? null : povertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER_POVERTY
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER_POVERTY
     *
     * @mbg.generated
     */
    public String getIdNumberPoverty() {
        return idNumberPoverty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER_POVERTY
     *
     * @param idNumberPoverty the value for TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER_POVERTY
     *
     * @mbg.generated
     */
    public void setIdNumberPoverty(String idNumberPoverty) {
        this.idNumberPoverty = idNumberPoverty == null ? null : idNumberPoverty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.IS_FIVE_INSURED
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.IS_FIVE_INSURED
     *
     * @mbg.generated
     */
    public String getIsFiveInsured() {
        return isFiveInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.IS_FIVE_INSURED
     *
     * @param isFiveInsured the value for TBL_BOTTOM_GUARANTEE_CIVIL.IS_FIVE_INSURED
     *
     * @mbg.generated
     */
    public void setIsFiveInsured(String isFiveInsured) {
        this.isFiveInsured = isFiveInsured == null ? null : isFiveInsured.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.FEEDING_MODE
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.FEEDING_MODE
     *
     * @mbg.generated
     */
    public String getFeedingMode() {
        return feedingMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.FEEDING_MODE
     *
     * @param feedingMode the value for TBL_BOTTOM_GUARANTEE_CIVIL.FEEDING_MODE
     *
     * @mbg.generated
     */
    public void setFeedingMode(String feedingMode) {
        this.feedingMode = feedingMode == null ? null : feedingMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.FIVE_PREMIUMS
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.FIVE_PREMIUMS
     *
     * @mbg.generated
     */
    public BigDecimal getFivePremiums() {
        return fivePremiums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.FIVE_PREMIUMS
     *
     * @param fivePremiums the value for TBL_BOTTOM_GUARANTEE_CIVIL.FIVE_PREMIUMS
     *
     * @mbg.generated
     */
    public void setFivePremiums(BigDecimal fivePremiums) {
        this.fivePremiums = fivePremiums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.IS_LOW_INSURED
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.IS_LOW_INSURED
     *
     * @mbg.generated
     */
    public String getIsLowInsured() {
        return isLowInsured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.IS_LOW_INSURED
     *
     * @param isLowInsured the value for TBL_BOTTOM_GUARANTEE_CIVIL.IS_LOW_INSURED
     *
     * @mbg.generated
     */
    public void setIsLowInsured(String isLowInsured) {
        this.isLowInsured = isLowInsured == null ? null : isLowInsured.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.NAME_OF_MEMBER
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.NAME_OF_MEMBER
     *
     * @mbg.generated
     */
    public String getNameOfMember() {
        return nameOfMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.NAME_OF_MEMBER
     *
     * @param nameOfMember the value for TBL_BOTTOM_GUARANTEE_CIVIL.NAME_OF_MEMBER
     *
     * @mbg.generated
     */
    public void setNameOfMember(String nameOfMember) {
        this.nameOfMember = nameOfMember == null ? null : nameOfMember.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.SEX
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.SEX
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.SEX
     *
     * @param sex the value for TBL_BOTTOM_GUARANTEE_CIVIL.SEX
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.RELATION_POVERTY
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.RELATION_POVERTY
     *
     * @mbg.generated
     */
    public String getRelationPoverty() {
        return relationPoverty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.RELATION_POVERTY
     *
     * @param relationPoverty the value for TBL_BOTTOM_GUARANTEE_CIVIL.RELATION_POVERTY
     *
     * @mbg.generated
     */
    public void setRelationPoverty(String relationPoverty) {
        this.relationPoverty = relationPoverty == null ? null : relationPoverty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER
     *
     * @mbg.generated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER
     *
     * @param idNumber the value for TBL_BOTTOM_GUARANTEE_CIVIL.ID_NUMBER
     *
     * @mbg.generated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_THE_POPULATION
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_THE_POPULATION
     *
     * @mbg.generated
     */
    public Long getProtectThePopulation() {
        return protectThePopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_THE_POPULATION
     *
     * @param protectThePopulation the value for TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_THE_POPULATION
     *
     * @mbg.generated
     */
    public void setProtectThePopulation(Long protectThePopulation) {
        this.protectThePopulation = protectThePopulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_TYPE
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_TYPE
     *
     * @mbg.generated
     */
    public String getProtectType() {
        return protectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_TYPE
     *
     * @param protectType the value for TBL_BOTTOM_GUARANTEE_CIVIL.PROTECT_TYPE
     *
     * @mbg.generated
     */
    public void setProtectType(String protectType) {
        this.protectType = protectType == null ? null : protectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.CLASSIFICATION_HEDGE
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.CLASSIFICATION_HEDGE
     *
     * @mbg.generated
     */
    public BigDecimal getClassificationHedge() {
        return classificationHedge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.CLASSIFICATION_HEDGE
     *
     * @param classificationHedge the value for TBL_BOTTOM_GUARANTEE_CIVIL.CLASSIFICATION_HEDGE
     *
     * @mbg.generated
     */
    public void setClassificationHedge(BigDecimal classificationHedge) {
        this.classificationHedge = classificationHedge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.LOW_PREMIUM
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.LOW_PREMIUM
     *
     * @mbg.generated
     */
    public BigDecimal getLowPremium() {
        return lowPremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.LOW_PREMIUM
     *
     * @param lowPremium the value for TBL_BOTTOM_GUARANTEE_CIVIL.LOW_PREMIUM
     *
     * @mbg.generated
     */
    public void setLowPremium(BigDecimal lowPremium) {
        this.lowPremium = lowPremium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.REMARKS
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.REMARKS
     *
     * @param remarks the value for TBL_BOTTOM_GUARANTEE_CIVIL.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.ZONE_YEAR
     *
     * @return the value of TBL_BOTTOM_GUARANTEE_CIVIL.ZONE_YEAR
     *
     * @mbg.generated
     */
    public Long getZoneYear() {
        return zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_GUARANTEE_CIVIL.ZONE_YEAR
     *
     * @param zoneYear the value for TBL_BOTTOM_GUARANTEE_CIVIL.ZONE_YEAR
     *
     * @mbg.generated
     */
    public void setZoneYear(Long zoneYear) {
        this.zoneYear = zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BottomGuaranteeCivilDD other = (BottomGuaranteeCivilDD) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getTownName() == null ? other.getTownName() == null : this.getTownName().equals(other.getTownName()))
            && (this.getVillageName() == null ? other.getVillageName() == null : this.getVillageName().equals(other.getVillageName()))
            && (this.getPovertyName() == null ? other.getPovertyName() == null : this.getPovertyName().equals(other.getPovertyName()))
            && (this.getIdNumberPoverty() == null ? other.getIdNumberPoverty() == null : this.getIdNumberPoverty().equals(other.getIdNumberPoverty()))
            && (this.getIsFiveInsured() == null ? other.getIsFiveInsured() == null : this.getIsFiveInsured().equals(other.getIsFiveInsured()))
            && (this.getFeedingMode() == null ? other.getFeedingMode() == null : this.getFeedingMode().equals(other.getFeedingMode()))
            && (this.getFivePremiums() == null ? other.getFivePremiums() == null : this.getFivePremiums().equals(other.getFivePremiums()))
            && (this.getIsLowInsured() == null ? other.getIsLowInsured() == null : this.getIsLowInsured().equals(other.getIsLowInsured()))
            && (this.getNameOfMember() == null ? other.getNameOfMember() == null : this.getNameOfMember().equals(other.getNameOfMember()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getRelationPoverty() == null ? other.getRelationPoverty() == null : this.getRelationPoverty().equals(other.getRelationPoverty()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getProtectThePopulation() == null ? other.getProtectThePopulation() == null : this.getProtectThePopulation().equals(other.getProtectThePopulation()))
            && (this.getProtectType() == null ? other.getProtectType() == null : this.getProtectType().equals(other.getProtectType()))
            && (this.getClassificationHedge() == null ? other.getClassificationHedge() == null : this.getClassificationHedge().equals(other.getClassificationHedge()))
            && (this.getLowPremium() == null ? other.getLowPremium() == null : this.getLowPremium().equals(other.getLowPremium()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getZoneYear() == null ? other.getZoneYear() == null : this.getZoneYear().equals(other.getZoneYear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getTownName() == null) ? 0 : getTownName().hashCode());
        result = prime * result + ((getVillageName() == null) ? 0 : getVillageName().hashCode());
        result = prime * result + ((getPovertyName() == null) ? 0 : getPovertyName().hashCode());
        result = prime * result + ((getIdNumberPoverty() == null) ? 0 : getIdNumberPoverty().hashCode());
        result = prime * result + ((getIsFiveInsured() == null) ? 0 : getIsFiveInsured().hashCode());
        result = prime * result + ((getFeedingMode() == null) ? 0 : getFeedingMode().hashCode());
        result = prime * result + ((getFivePremiums() == null) ? 0 : getFivePremiums().hashCode());
        result = prime * result + ((getIsLowInsured() == null) ? 0 : getIsLowInsured().hashCode());
        result = prime * result + ((getNameOfMember() == null) ? 0 : getNameOfMember().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getRelationPoverty() == null) ? 0 : getRelationPoverty().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getProtectThePopulation() == null) ? 0 : getProtectThePopulation().hashCode());
        result = prime * result + ((getProtectType() == null) ? 0 : getProtectType().hashCode());
        result = prime * result + ((getClassificationHedge() == null) ? 0 : getClassificationHedge().hashCode());
        result = prime * result + ((getLowPremium() == null) ? 0 : getLowPremium().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getZoneYear() == null) ? 0 : getZoneYear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_GUARANTEE_CIVIL
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", districtName=").append(districtName);
        sb.append(", townName=").append(townName);
        sb.append(", villageName=").append(villageName);
        sb.append(", povertyName=").append(povertyName);
        sb.append(", idNumberPoverty=").append(idNumberPoverty);
        sb.append(", isFiveInsured=").append(isFiveInsured);
        sb.append(", feedingMode=").append(feedingMode);
        sb.append(", fivePremiums=").append(fivePremiums);
        sb.append(", isLowInsured=").append(isLowInsured);
        sb.append(", nameOfMember=").append(nameOfMember);
        sb.append(", sex=").append(sex);
        sb.append(", relationPoverty=").append(relationPoverty);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", protectThePopulation=").append(protectThePopulation);
        sb.append(", protectType=").append(protectType);
        sb.append(", classificationHedge=").append(classificationHedge);
        sb.append(", lowPremium=").append(lowPremium);
        sb.append(", remarks=").append(remarks);
        sb.append(", zoneYear=").append(zoneYear);
        sb.append("]");
        return sb.toString();
    }
}