package com.sysh.entity.helpmea;

import java.io.Serializable;

public class BottomDisabledDD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.DISTRICT_NAME
     *
     * @mbg.generated
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.TOWN_NAME
     *
     * @mbg.generated
     */
    private String townName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.VILLAGE_NAME
     *
     * @mbg.generated
     */
    private String villageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.ID_NUMBER
     *
     * @mbg.generated
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.DISABILITY_CATEGORY
     *
     * @mbg.generated
     */
    private String disabilityCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.DISABLED_LEVEL
     *
     * @mbg.generated
     */
    private String disabledLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.CERTIFICATION_TIME
     *
     * @mbg.generated
     */
    private String certificationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.CHILD_REHABILITATION_ASS
     *
     * @mbg.generated
     */
    private Long childRehabilitationAss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.SPIRIT_REHABILITATION_ASS
     *
     * @mbg.generated
     */
    private Long spiritRehabilitationAss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.AUXILIARY_NUMBER
     *
     * @mbg.generated
     */
    private Long auxiliaryNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.DISABLED_BREED_NUMBER
     *
     * @mbg.generated
     */
    private Long disabledBreedNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.SELF_PROPELLED
     *
     * @mbg.generated
     */
    private Long selfPropelled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.DISABLED_SELF_PROPELLED
     *
     * @mbg.generated
     */
    private Long disabledSelfPropelled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.LONG_DISTANCE_EDUCATION
     *
     * @mbg.generated
     */
    private Long longDistanceEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.BARRIER_FREE_RECONSTRUCTION
     *
     * @mbg.generated
     */
    private Long barrierFreeReconstruction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_BOTTOM_DISABLED.ZONE_YEAR
     *
     * @mbg.generated
     */
    private Long zoneYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.ID
     *
     * @return the value of TBL_BOTTOM_DISABLED.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.ID
     *
     * @param id the value for TBL_BOTTOM_DISABLED.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.DISTRICT_NAME
     *
     * @return the value of TBL_BOTTOM_DISABLED.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.DISTRICT_NAME
     *
     * @param districtName the value for TBL_BOTTOM_DISABLED.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.TOWN_NAME
     *
     * @return the value of TBL_BOTTOM_DISABLED.TOWN_NAME
     *
     * @mbg.generated
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.TOWN_NAME
     *
     * @param townName the value for TBL_BOTTOM_DISABLED.TOWN_NAME
     *
     * @mbg.generated
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.VILLAGE_NAME
     *
     * @return the value of TBL_BOTTOM_DISABLED.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.VILLAGE_NAME
     *
     * @param villageName the value for TBL_BOTTOM_DISABLED.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public void setVillageName(String villageName) {
        this.villageName = villageName == null ? null : villageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.NAME
     *
     * @return the value of TBL_BOTTOM_DISABLED.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.NAME
     *
     * @param name the value for TBL_BOTTOM_DISABLED.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.ID_NUMBER
     *
     * @return the value of TBL_BOTTOM_DISABLED.ID_NUMBER
     *
     * @mbg.generated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.ID_NUMBER
     *
     * @param idNumber the value for TBL_BOTTOM_DISABLED.ID_NUMBER
     *
     * @mbg.generated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.DISABILITY_CATEGORY
     *
     * @return the value of TBL_BOTTOM_DISABLED.DISABILITY_CATEGORY
     *
     * @mbg.generated
     */
    public String getDisabilityCategory() {
        return disabilityCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.DISABILITY_CATEGORY
     *
     * @param disabilityCategory the value for TBL_BOTTOM_DISABLED.DISABILITY_CATEGORY
     *
     * @mbg.generated
     */
    public void setDisabilityCategory(String disabilityCategory) {
        this.disabilityCategory = disabilityCategory == null ? null : disabilityCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.DISABLED_LEVEL
     *
     * @return the value of TBL_BOTTOM_DISABLED.DISABLED_LEVEL
     *
     * @mbg.generated
     */
    public String getDisabledLevel() {
        return disabledLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.DISABLED_LEVEL
     *
     * @param disabledLevel the value for TBL_BOTTOM_DISABLED.DISABLED_LEVEL
     *
     * @mbg.generated
     */
    public void setDisabledLevel(String disabledLevel) {
        this.disabledLevel = disabledLevel == null ? null : disabledLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.CERTIFICATION_TIME
     *
     * @return the value of TBL_BOTTOM_DISABLED.CERTIFICATION_TIME
     *
     * @mbg.generated
     */
    public String getCertificationTime() {
        return certificationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.CERTIFICATION_TIME
     *
     * @param certificationTime the value for TBL_BOTTOM_DISABLED.CERTIFICATION_TIME
     *
     * @mbg.generated
     */
    public void setCertificationTime(String certificationTime) {
        this.certificationTime = certificationTime == null ? null : certificationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.CHILD_REHABILITATION_ASS
     *
     * @return the value of TBL_BOTTOM_DISABLED.CHILD_REHABILITATION_ASS
     *
     * @mbg.generated
     */
    public Long getChildRehabilitationAss() {
        return childRehabilitationAss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.CHILD_REHABILITATION_ASS
     *
     * @param childRehabilitationAss the value for TBL_BOTTOM_DISABLED.CHILD_REHABILITATION_ASS
     *
     * @mbg.generated
     */
    public void setChildRehabilitationAss(Long childRehabilitationAss) {
        this.childRehabilitationAss = childRehabilitationAss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.SPIRIT_REHABILITATION_ASS
     *
     * @return the value of TBL_BOTTOM_DISABLED.SPIRIT_REHABILITATION_ASS
     *
     * @mbg.generated
     */
    public Long getSpiritRehabilitationAss() {
        return spiritRehabilitationAss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.SPIRIT_REHABILITATION_ASS
     *
     * @param spiritRehabilitationAss the value for TBL_BOTTOM_DISABLED.SPIRIT_REHABILITATION_ASS
     *
     * @mbg.generated
     */
    public void setSpiritRehabilitationAss(Long spiritRehabilitationAss) {
        this.spiritRehabilitationAss = spiritRehabilitationAss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.AUXILIARY_NUMBER
     *
     * @return the value of TBL_BOTTOM_DISABLED.AUXILIARY_NUMBER
     *
     * @mbg.generated
     */
    public Long getAuxiliaryNumber() {
        return auxiliaryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.AUXILIARY_NUMBER
     *
     * @param auxiliaryNumber the value for TBL_BOTTOM_DISABLED.AUXILIARY_NUMBER
     *
     * @mbg.generated
     */
    public void setAuxiliaryNumber(Long auxiliaryNumber) {
        this.auxiliaryNumber = auxiliaryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.DISABLED_BREED_NUMBER
     *
     * @return the value of TBL_BOTTOM_DISABLED.DISABLED_BREED_NUMBER
     *
     * @mbg.generated
     */
    public Long getDisabledBreedNumber() {
        return disabledBreedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.DISABLED_BREED_NUMBER
     *
     * @param disabledBreedNumber the value for TBL_BOTTOM_DISABLED.DISABLED_BREED_NUMBER
     *
     * @mbg.generated
     */
    public void setDisabledBreedNumber(Long disabledBreedNumber) {
        this.disabledBreedNumber = disabledBreedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.SELF_PROPELLED
     *
     * @return the value of TBL_BOTTOM_DISABLED.SELF_PROPELLED
     *
     * @mbg.generated
     */
    public Long getSelfPropelled() {
        return selfPropelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.SELF_PROPELLED
     *
     * @param selfPropelled the value for TBL_BOTTOM_DISABLED.SELF_PROPELLED
     *
     * @mbg.generated
     */
    public void setSelfPropelled(Long selfPropelled) {
        this.selfPropelled = selfPropelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.DISABLED_SELF_PROPELLED
     *
     * @return the value of TBL_BOTTOM_DISABLED.DISABLED_SELF_PROPELLED
     *
     * @mbg.generated
     */
    public Long getDisabledSelfPropelled() {
        return disabledSelfPropelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.DISABLED_SELF_PROPELLED
     *
     * @param disabledSelfPropelled the value for TBL_BOTTOM_DISABLED.DISABLED_SELF_PROPELLED
     *
     * @mbg.generated
     */
    public void setDisabledSelfPropelled(Long disabledSelfPropelled) {
        this.disabledSelfPropelled = disabledSelfPropelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.LONG_DISTANCE_EDUCATION
     *
     * @return the value of TBL_BOTTOM_DISABLED.LONG_DISTANCE_EDUCATION
     *
     * @mbg.generated
     */
    public Long getLongDistanceEducation() {
        return longDistanceEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.LONG_DISTANCE_EDUCATION
     *
     * @param longDistanceEducation the value for TBL_BOTTOM_DISABLED.LONG_DISTANCE_EDUCATION
     *
     * @mbg.generated
     */
    public void setLongDistanceEducation(Long longDistanceEducation) {
        this.longDistanceEducation = longDistanceEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.BARRIER_FREE_RECONSTRUCTION
     *
     * @return the value of TBL_BOTTOM_DISABLED.BARRIER_FREE_RECONSTRUCTION
     *
     * @mbg.generated
     */
    public Long getBarrierFreeReconstruction() {
        return barrierFreeReconstruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.BARRIER_FREE_RECONSTRUCTION
     *
     * @param barrierFreeReconstruction the value for TBL_BOTTOM_DISABLED.BARRIER_FREE_RECONSTRUCTION
     *
     * @mbg.generated
     */
    public void setBarrierFreeReconstruction(Long barrierFreeReconstruction) {
        this.barrierFreeReconstruction = barrierFreeReconstruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.REMARKS
     *
     * @return the value of TBL_BOTTOM_DISABLED.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.REMARKS
     *
     * @param remarks the value for TBL_BOTTOM_DISABLED.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_BOTTOM_DISABLED.ZONE_YEAR
     *
     * @return the value of TBL_BOTTOM_DISABLED.ZONE_YEAR
     *
     * @mbg.generated
     */
    public Long getZoneYear() {
        return zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_BOTTOM_DISABLED.ZONE_YEAR
     *
     * @param zoneYear the value for TBL_BOTTOM_DISABLED.ZONE_YEAR
     *
     * @mbg.generated
     */
    public void setZoneYear(Long zoneYear) {
        this.zoneYear = zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BottomDisabledDD other = (BottomDisabledDD) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getTownName() == null ? other.getTownName() == null : this.getTownName().equals(other.getTownName()))
            && (this.getVillageName() == null ? other.getVillageName() == null : this.getVillageName().equals(other.getVillageName()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getDisabilityCategory() == null ? other.getDisabilityCategory() == null : this.getDisabilityCategory().equals(other.getDisabilityCategory()))
            && (this.getDisabledLevel() == null ? other.getDisabledLevel() == null : this.getDisabledLevel().equals(other.getDisabledLevel()))
            && (this.getCertificationTime() == null ? other.getCertificationTime() == null : this.getCertificationTime().equals(other.getCertificationTime()))
            && (this.getChildRehabilitationAss() == null ? other.getChildRehabilitationAss() == null : this.getChildRehabilitationAss().equals(other.getChildRehabilitationAss()))
            && (this.getSpiritRehabilitationAss() == null ? other.getSpiritRehabilitationAss() == null : this.getSpiritRehabilitationAss().equals(other.getSpiritRehabilitationAss()))
            && (this.getAuxiliaryNumber() == null ? other.getAuxiliaryNumber() == null : this.getAuxiliaryNumber().equals(other.getAuxiliaryNumber()))
            && (this.getDisabledBreedNumber() == null ? other.getDisabledBreedNumber() == null : this.getDisabledBreedNumber().equals(other.getDisabledBreedNumber()))
            && (this.getSelfPropelled() == null ? other.getSelfPropelled() == null : this.getSelfPropelled().equals(other.getSelfPropelled()))
            && (this.getDisabledSelfPropelled() == null ? other.getDisabledSelfPropelled() == null : this.getDisabledSelfPropelled().equals(other.getDisabledSelfPropelled()))
            && (this.getLongDistanceEducation() == null ? other.getLongDistanceEducation() == null : this.getLongDistanceEducation().equals(other.getLongDistanceEducation()))
            && (this.getBarrierFreeReconstruction() == null ? other.getBarrierFreeReconstruction() == null : this.getBarrierFreeReconstruction().equals(other.getBarrierFreeReconstruction()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getZoneYear() == null ? other.getZoneYear() == null : this.getZoneYear().equals(other.getZoneYear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getTownName() == null) ? 0 : getTownName().hashCode());
        result = prime * result + ((getVillageName() == null) ? 0 : getVillageName().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getDisabilityCategory() == null) ? 0 : getDisabilityCategory().hashCode());
        result = prime * result + ((getDisabledLevel() == null) ? 0 : getDisabledLevel().hashCode());
        result = prime * result + ((getCertificationTime() == null) ? 0 : getCertificationTime().hashCode());
        result = prime * result + ((getChildRehabilitationAss() == null) ? 0 : getChildRehabilitationAss().hashCode());
        result = prime * result + ((getSpiritRehabilitationAss() == null) ? 0 : getSpiritRehabilitationAss().hashCode());
        result = prime * result + ((getAuxiliaryNumber() == null) ? 0 : getAuxiliaryNumber().hashCode());
        result = prime * result + ((getDisabledBreedNumber() == null) ? 0 : getDisabledBreedNumber().hashCode());
        result = prime * result + ((getSelfPropelled() == null) ? 0 : getSelfPropelled().hashCode());
        result = prime * result + ((getDisabledSelfPropelled() == null) ? 0 : getDisabledSelfPropelled().hashCode());
        result = prime * result + ((getLongDistanceEducation() == null) ? 0 : getLongDistanceEducation().hashCode());
        result = prime * result + ((getBarrierFreeReconstruction() == null) ? 0 : getBarrierFreeReconstruction().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getZoneYear() == null) ? 0 : getZoneYear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BOTTOM_DISABLED
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", districtName=").append(districtName);
        sb.append(", townName=").append(townName);
        sb.append(", villageName=").append(villageName);
        sb.append(", name=").append(name);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", disabilityCategory=").append(disabilityCategory);
        sb.append(", disabledLevel=").append(disabledLevel);
        sb.append(", certificationTime=").append(certificationTime);
        sb.append(", childRehabilitationAss=").append(childRehabilitationAss);
        sb.append(", spiritRehabilitationAss=").append(spiritRehabilitationAss);
        sb.append(", auxiliaryNumber=").append(auxiliaryNumber);
        sb.append(", disabledBreedNumber=").append(disabledBreedNumber);
        sb.append(", selfPropelled=").append(selfPropelled);
        sb.append(", disabledSelfPropelled=").append(disabledSelfPropelled);
        sb.append(", longDistanceEducation=").append(longDistanceEducation);
        sb.append(", barrierFreeReconstruction=").append(barrierFreeReconstruction);
        sb.append(", remarks=").append(remarks);
        sb.append(", zoneYear=").append(zoneYear);
        sb.append("]");
        return sb.toString();
    }
}