package com.sysh.entity.helpmea;

import java.io.Serializable;
import java.math.BigDecimal;

public class EcologicalPovertyDD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.DISTRICT_NAME
     *
     * @mbg.generated
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.TOWN_NAME
     *
     * @mbg.generated
     */
    private String townName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.VILLAGE_NAME
     *
     * @mbg.generated
     */
    private String villageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.ID_NUMBER
     *
     * @mbg.generated
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.RELATION_HOUSEHOLD
     *
     * @mbg.generated
     */
    private String relationHousehold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.POVERTY_NAME
     *
     * @mbg.generated
     */
    private String povertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.IS_RETURN_FOREST
     *
     * @mbg.generated
     */
    private String isReturnForest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_AREA
     *
     * @mbg.generated
     */
    private BigDecimal returnForestArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_GRANT
     *
     * @mbg.generated
     */
    private BigDecimal returnForestGrant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.IS_ECOLOGY_COMP
     *
     * @mbg.generated
     */
    private String isEcologyComp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_AREA
     *
     * @mbg.generated
     */
    private BigDecimal ecologyCompArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_EVERY_YEAR
     *
     * @mbg.generated
     */
    private BigDecimal ecologyCompEveryYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.FOREST_RANGEREMPLOY
     *
     * @mbg.generated
     */
    private BigDecimal forestRangeremploy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_ECOLOGICAL_POVERTY.ZONE_YEAR
     *
     * @mbg.generated
     */
    private Long zoneYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.ID
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.ID
     *
     * @param id the value for TBL_ECOLOGICAL_POVERTY.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.DISTRICT_NAME
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.DISTRICT_NAME
     *
     * @param districtName the value for TBL_ECOLOGICAL_POVERTY.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.TOWN_NAME
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.TOWN_NAME
     *
     * @mbg.generated
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.TOWN_NAME
     *
     * @param townName the value for TBL_ECOLOGICAL_POVERTY.TOWN_NAME
     *
     * @mbg.generated
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.VILLAGE_NAME
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.VILLAGE_NAME
     *
     * @param villageName the value for TBL_ECOLOGICAL_POVERTY.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public void setVillageName(String villageName) {
        this.villageName = villageName == null ? null : villageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.NAME
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.NAME
     *
     * @param name the value for TBL_ECOLOGICAL_POVERTY.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.ID_NUMBER
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.ID_NUMBER
     *
     * @mbg.generated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.ID_NUMBER
     *
     * @param idNumber the value for TBL_ECOLOGICAL_POVERTY.ID_NUMBER
     *
     * @mbg.generated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.RELATION_HOUSEHOLD
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.RELATION_HOUSEHOLD
     *
     * @mbg.generated
     */
    public String getRelationHousehold() {
        return relationHousehold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.RELATION_HOUSEHOLD
     *
     * @param relationHousehold the value for TBL_ECOLOGICAL_POVERTY.RELATION_HOUSEHOLD
     *
     * @mbg.generated
     */
    public void setRelationHousehold(String relationHousehold) {
        this.relationHousehold = relationHousehold == null ? null : relationHousehold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.POVERTY_NAME
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.POVERTY_NAME
     *
     * @mbg.generated
     */
    public String getPovertyName() {
        return povertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.POVERTY_NAME
     *
     * @param povertyName the value for TBL_ECOLOGICAL_POVERTY.POVERTY_NAME
     *
     * @mbg.generated
     */
    public void setPovertyName(String povertyName) {
        this.povertyName = povertyName == null ? null : povertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.IS_RETURN_FOREST
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.IS_RETURN_FOREST
     *
     * @mbg.generated
     */
    public String getIsReturnForest() {
        return isReturnForest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.IS_RETURN_FOREST
     *
     * @param isReturnForest the value for TBL_ECOLOGICAL_POVERTY.IS_RETURN_FOREST
     *
     * @mbg.generated
     */
    public void setIsReturnForest(String isReturnForest) {
        this.isReturnForest = isReturnForest == null ? null : isReturnForest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_AREA
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_AREA
     *
     * @mbg.generated
     */
    public BigDecimal getReturnForestArea() {
        return returnForestArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_AREA
     *
     * @param returnForestArea the value for TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_AREA
     *
     * @mbg.generated
     */
    public void setReturnForestArea(BigDecimal returnForestArea) {
        this.returnForestArea = returnForestArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_GRANT
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_GRANT
     *
     * @mbg.generated
     */
    public BigDecimal getReturnForestGrant() {
        return returnForestGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_GRANT
     *
     * @param returnForestGrant the value for TBL_ECOLOGICAL_POVERTY.RETURN_FOREST_GRANT
     *
     * @mbg.generated
     */
    public void setReturnForestGrant(BigDecimal returnForestGrant) {
        this.returnForestGrant = returnForestGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.IS_ECOLOGY_COMP
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.IS_ECOLOGY_COMP
     *
     * @mbg.generated
     */
    public String getIsEcologyComp() {
        return isEcologyComp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.IS_ECOLOGY_COMP
     *
     * @param isEcologyComp the value for TBL_ECOLOGICAL_POVERTY.IS_ECOLOGY_COMP
     *
     * @mbg.generated
     */
    public void setIsEcologyComp(String isEcologyComp) {
        this.isEcologyComp = isEcologyComp == null ? null : isEcologyComp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_AREA
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_AREA
     *
     * @mbg.generated
     */
    public BigDecimal getEcologyCompArea() {
        return ecologyCompArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_AREA
     *
     * @param ecologyCompArea the value for TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_AREA
     *
     * @mbg.generated
     */
    public void setEcologyCompArea(BigDecimal ecologyCompArea) {
        this.ecologyCompArea = ecologyCompArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_EVERY_YEAR
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_EVERY_YEAR
     *
     * @mbg.generated
     */
    public BigDecimal getEcologyCompEveryYear() {
        return ecologyCompEveryYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_EVERY_YEAR
     *
     * @param ecologyCompEveryYear the value for TBL_ECOLOGICAL_POVERTY.ECOLOGY_COMP_EVERY_YEAR
     *
     * @mbg.generated
     */
    public void setEcologyCompEveryYear(BigDecimal ecologyCompEveryYear) {
        this.ecologyCompEveryYear = ecologyCompEveryYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.FOREST_RANGEREMPLOY
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.FOREST_RANGEREMPLOY
     *
     * @mbg.generated
     */
    public BigDecimal getForestRangeremploy() {
        return forestRangeremploy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.FOREST_RANGEREMPLOY
     *
     * @param forestRangeremploy the value for TBL_ECOLOGICAL_POVERTY.FOREST_RANGEREMPLOY
     *
     * @mbg.generated
     */
    public void setForestRangeremploy(BigDecimal forestRangeremploy) {
        this.forestRangeremploy = forestRangeremploy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.REMARKS
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.REMARKS
     *
     * @param remarks the value for TBL_ECOLOGICAL_POVERTY.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_ECOLOGICAL_POVERTY.ZONE_YEAR
     *
     * @return the value of TBL_ECOLOGICAL_POVERTY.ZONE_YEAR
     *
     * @mbg.generated
     */
    public Long getZoneYear() {
        return zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_ECOLOGICAL_POVERTY.ZONE_YEAR
     *
     * @param zoneYear the value for TBL_ECOLOGICAL_POVERTY.ZONE_YEAR
     *
     * @mbg.generated
     */
    public void setZoneYear(Long zoneYear) {
        this.zoneYear = zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EcologicalPovertyDD other = (EcologicalPovertyDD) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getTownName() == null ? other.getTownName() == null : this.getTownName().equals(other.getTownName()))
            && (this.getVillageName() == null ? other.getVillageName() == null : this.getVillageName().equals(other.getVillageName()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getRelationHousehold() == null ? other.getRelationHousehold() == null : this.getRelationHousehold().equals(other.getRelationHousehold()))
            && (this.getPovertyName() == null ? other.getPovertyName() == null : this.getPovertyName().equals(other.getPovertyName()))
            && (this.getIsReturnForest() == null ? other.getIsReturnForest() == null : this.getIsReturnForest().equals(other.getIsReturnForest()))
            && (this.getReturnForestArea() == null ? other.getReturnForestArea() == null : this.getReturnForestArea().equals(other.getReturnForestArea()))
            && (this.getReturnForestGrant() == null ? other.getReturnForestGrant() == null : this.getReturnForestGrant().equals(other.getReturnForestGrant()))
            && (this.getIsEcologyComp() == null ? other.getIsEcologyComp() == null : this.getIsEcologyComp().equals(other.getIsEcologyComp()))
            && (this.getEcologyCompArea() == null ? other.getEcologyCompArea() == null : this.getEcologyCompArea().equals(other.getEcologyCompArea()))
            && (this.getEcologyCompEveryYear() == null ? other.getEcologyCompEveryYear() == null : this.getEcologyCompEveryYear().equals(other.getEcologyCompEveryYear()))
            && (this.getForestRangeremploy() == null ? other.getForestRangeremploy() == null : this.getForestRangeremploy().equals(other.getForestRangeremploy()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getZoneYear() == null ? other.getZoneYear() == null : this.getZoneYear().equals(other.getZoneYear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getTownName() == null) ? 0 : getTownName().hashCode());
        result = prime * result + ((getVillageName() == null) ? 0 : getVillageName().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getRelationHousehold() == null) ? 0 : getRelationHousehold().hashCode());
        result = prime * result + ((getPovertyName() == null) ? 0 : getPovertyName().hashCode());
        result = prime * result + ((getIsReturnForest() == null) ? 0 : getIsReturnForest().hashCode());
        result = prime * result + ((getReturnForestArea() == null) ? 0 : getReturnForestArea().hashCode());
        result = prime * result + ((getReturnForestGrant() == null) ? 0 : getReturnForestGrant().hashCode());
        result = prime * result + ((getIsEcologyComp() == null) ? 0 : getIsEcologyComp().hashCode());
        result = prime * result + ((getEcologyCompArea() == null) ? 0 : getEcologyCompArea().hashCode());
        result = prime * result + ((getEcologyCompEveryYear() == null) ? 0 : getEcologyCompEveryYear().hashCode());
        result = prime * result + ((getForestRangeremploy() == null) ? 0 : getForestRangeremploy().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getZoneYear() == null) ? 0 : getZoneYear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_ECOLOGICAL_POVERTY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", districtName=").append(districtName);
        sb.append(", townName=").append(townName);
        sb.append(", villageName=").append(villageName);
        sb.append(", name=").append(name);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", relationHousehold=").append(relationHousehold);
        sb.append(", povertyName=").append(povertyName);
        sb.append(", isReturnForest=").append(isReturnForest);
        sb.append(", returnForestArea=").append(returnForestArea);
        sb.append(", returnForestGrant=").append(returnForestGrant);
        sb.append(", isEcologyComp=").append(isEcologyComp);
        sb.append(", ecologyCompArea=").append(ecologyCompArea);
        sb.append(", ecologyCompEveryYear=").append(ecologyCompEveryYear);
        sb.append(", forestRangeremploy=").append(forestRangeremploy);
        sb.append(", remarks=").append(remarks);
        sb.append(", zoneYear=").append(zoneYear);
        sb.append("]");
        return sb.toString();
    }
}