package com.sysh.entity.helpmea;

import java.io.Serializable;

public class EducationDD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.DISTRICT_NAME
     *
     * @mbg.generated
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.TOWN_NAME
     *
     * @mbg.generated
     */
    private String townName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.VILLAGE_NAME
     *
     * @mbg.generated
     */
    private String villageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.SEX
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.ID_NUMBER
     *
     * @mbg.generated
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_DROP_SCHOOL
     *
     * @mbg.generated
     */
    private String isDropSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.STUDY_GRADE
     *
     * @mbg.generated
     */
    private String studyGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.STUDY_SCHOOL_NAME
     *
     * @mbg.generated
     */
    private String studySchoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_TEACHING
     *
     * @mbg.generated
     */
    private String isTeaching;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_ATTENDANT
     *
     * @mbg.generated
     */
    private String isAttendant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_SPECIAL_EDUCATION
     *
     * @mbg.generated
     */
    private String isSpecialEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_INFANT_SUBSIDY
     *
     * @mbg.generated
     */
    private String isInfantSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_BOARDING_STUDENTS
     *
     * @mbg.generated
     */
    private String isBoardingStudents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_HIGH_SCH_GRANT
     *
     * @mbg.generated
     */
    private String isHighSchGrant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_SCONDARY_SCH_GRANT
     *
     * @mbg.generated
     */
    private String isScondarySchGrant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_SCONDARY_SCH_TUITION
     *
     * @mbg.generated
     */
    private String isScondarySchTuition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_POVERTY_SCONDARY_GRANT
     *
     * @mbg.generated
     */
    private String isPovertyScondaryGrant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_POVERTY_HIGH_GRANT
     *
     * @mbg.generated
     */
    private String isPovertyHighGrant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_NUTRITION_PLAN
     *
     * @mbg.generated
     */
    private String isNutritionPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.IS_INSURANCE_PREMIUMS
     *
     * @mbg.generated
     */
    private String isInsurancePremiums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.OTHERS
     *
     * @mbg.generated
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EDUCATION.ZONE_YEAR
     *
     * @mbg.generated
     */
    private Long zoneYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.ID
     *
     * @return the value of TBL_EDUCATION.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.ID
     *
     * @param id the value for TBL_EDUCATION.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.DISTRICT_NAME
     *
     * @return the value of TBL_EDUCATION.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.DISTRICT_NAME
     *
     * @param districtName the value for TBL_EDUCATION.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.TOWN_NAME
     *
     * @return the value of TBL_EDUCATION.TOWN_NAME
     *
     * @mbg.generated
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.TOWN_NAME
     *
     * @param townName the value for TBL_EDUCATION.TOWN_NAME
     *
     * @mbg.generated
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.VILLAGE_NAME
     *
     * @return the value of TBL_EDUCATION.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.VILLAGE_NAME
     *
     * @param villageName the value for TBL_EDUCATION.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public void setVillageName(String villageName) {
        this.villageName = villageName == null ? null : villageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.NAME
     *
     * @return the value of TBL_EDUCATION.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.NAME
     *
     * @param name the value for TBL_EDUCATION.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.SEX
     *
     * @return the value of TBL_EDUCATION.SEX
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.SEX
     *
     * @param sex the value for TBL_EDUCATION.SEX
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.ID_NUMBER
     *
     * @return the value of TBL_EDUCATION.ID_NUMBER
     *
     * @mbg.generated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.ID_NUMBER
     *
     * @param idNumber the value for TBL_EDUCATION.ID_NUMBER
     *
     * @mbg.generated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_DROP_SCHOOL
     *
     * @return the value of TBL_EDUCATION.IS_DROP_SCHOOL
     *
     * @mbg.generated
     */
    public String getIsDropSchool() {
        return isDropSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_DROP_SCHOOL
     *
     * @param isDropSchool the value for TBL_EDUCATION.IS_DROP_SCHOOL
     *
     * @mbg.generated
     */
    public void setIsDropSchool(String isDropSchool) {
        this.isDropSchool = isDropSchool == null ? null : isDropSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.STUDY_GRADE
     *
     * @return the value of TBL_EDUCATION.STUDY_GRADE
     *
     * @mbg.generated
     */
    public String getStudyGrade() {
        return studyGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.STUDY_GRADE
     *
     * @param studyGrade the value for TBL_EDUCATION.STUDY_GRADE
     *
     * @mbg.generated
     */
    public void setStudyGrade(String studyGrade) {
        this.studyGrade = studyGrade == null ? null : studyGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.STUDY_SCHOOL_NAME
     *
     * @return the value of TBL_EDUCATION.STUDY_SCHOOL_NAME
     *
     * @mbg.generated
     */
    public String getStudySchoolName() {
        return studySchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.STUDY_SCHOOL_NAME
     *
     * @param studySchoolName the value for TBL_EDUCATION.STUDY_SCHOOL_NAME
     *
     * @mbg.generated
     */
    public void setStudySchoolName(String studySchoolName) {
        this.studySchoolName = studySchoolName == null ? null : studySchoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_TEACHING
     *
     * @return the value of TBL_EDUCATION.IS_TEACHING
     *
     * @mbg.generated
     */
    public String getIsTeaching() {
        return isTeaching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_TEACHING
     *
     * @param isTeaching the value for TBL_EDUCATION.IS_TEACHING
     *
     * @mbg.generated
     */
    public void setIsTeaching(String isTeaching) {
        this.isTeaching = isTeaching == null ? null : isTeaching.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_ATTENDANT
     *
     * @return the value of TBL_EDUCATION.IS_ATTENDANT
     *
     * @mbg.generated
     */
    public String getIsAttendant() {
        return isAttendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_ATTENDANT
     *
     * @param isAttendant the value for TBL_EDUCATION.IS_ATTENDANT
     *
     * @mbg.generated
     */
    public void setIsAttendant(String isAttendant) {
        this.isAttendant = isAttendant == null ? null : isAttendant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_SPECIAL_EDUCATION
     *
     * @return the value of TBL_EDUCATION.IS_SPECIAL_EDUCATION
     *
     * @mbg.generated
     */
    public String getIsSpecialEducation() {
        return isSpecialEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_SPECIAL_EDUCATION
     *
     * @param isSpecialEducation the value for TBL_EDUCATION.IS_SPECIAL_EDUCATION
     *
     * @mbg.generated
     */
    public void setIsSpecialEducation(String isSpecialEducation) {
        this.isSpecialEducation = isSpecialEducation == null ? null : isSpecialEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_INFANT_SUBSIDY
     *
     * @return the value of TBL_EDUCATION.IS_INFANT_SUBSIDY
     *
     * @mbg.generated
     */
    public String getIsInfantSubsidy() {
        return isInfantSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_INFANT_SUBSIDY
     *
     * @param isInfantSubsidy the value for TBL_EDUCATION.IS_INFANT_SUBSIDY
     *
     * @mbg.generated
     */
    public void setIsInfantSubsidy(String isInfantSubsidy) {
        this.isInfantSubsidy = isInfantSubsidy == null ? null : isInfantSubsidy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_BOARDING_STUDENTS
     *
     * @return the value of TBL_EDUCATION.IS_BOARDING_STUDENTS
     *
     * @mbg.generated
     */
    public String getIsBoardingStudents() {
        return isBoardingStudents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_BOARDING_STUDENTS
     *
     * @param isBoardingStudents the value for TBL_EDUCATION.IS_BOARDING_STUDENTS
     *
     * @mbg.generated
     */
    public void setIsBoardingStudents(String isBoardingStudents) {
        this.isBoardingStudents = isBoardingStudents == null ? null : isBoardingStudents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_HIGH_SCH_GRANT
     *
     * @return the value of TBL_EDUCATION.IS_HIGH_SCH_GRANT
     *
     * @mbg.generated
     */
    public String getIsHighSchGrant() {
        return isHighSchGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_HIGH_SCH_GRANT
     *
     * @param isHighSchGrant the value for TBL_EDUCATION.IS_HIGH_SCH_GRANT
     *
     * @mbg.generated
     */
    public void setIsHighSchGrant(String isHighSchGrant) {
        this.isHighSchGrant = isHighSchGrant == null ? null : isHighSchGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_SCONDARY_SCH_GRANT
     *
     * @return the value of TBL_EDUCATION.IS_SCONDARY_SCH_GRANT
     *
     * @mbg.generated
     */
    public String getIsScondarySchGrant() {
        return isScondarySchGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_SCONDARY_SCH_GRANT
     *
     * @param isScondarySchGrant the value for TBL_EDUCATION.IS_SCONDARY_SCH_GRANT
     *
     * @mbg.generated
     */
    public void setIsScondarySchGrant(String isScondarySchGrant) {
        this.isScondarySchGrant = isScondarySchGrant == null ? null : isScondarySchGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_SCONDARY_SCH_TUITION
     *
     * @return the value of TBL_EDUCATION.IS_SCONDARY_SCH_TUITION
     *
     * @mbg.generated
     */
    public String getIsScondarySchTuition() {
        return isScondarySchTuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_SCONDARY_SCH_TUITION
     *
     * @param isScondarySchTuition the value for TBL_EDUCATION.IS_SCONDARY_SCH_TUITION
     *
     * @mbg.generated
     */
    public void setIsScondarySchTuition(String isScondarySchTuition) {
        this.isScondarySchTuition = isScondarySchTuition == null ? null : isScondarySchTuition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_POVERTY_SCONDARY_GRANT
     *
     * @return the value of TBL_EDUCATION.IS_POVERTY_SCONDARY_GRANT
     *
     * @mbg.generated
     */
    public String getIsPovertyScondaryGrant() {
        return isPovertyScondaryGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_POVERTY_SCONDARY_GRANT
     *
     * @param isPovertyScondaryGrant the value for TBL_EDUCATION.IS_POVERTY_SCONDARY_GRANT
     *
     * @mbg.generated
     */
    public void setIsPovertyScondaryGrant(String isPovertyScondaryGrant) {
        this.isPovertyScondaryGrant = isPovertyScondaryGrant == null ? null : isPovertyScondaryGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_POVERTY_HIGH_GRANT
     *
     * @return the value of TBL_EDUCATION.IS_POVERTY_HIGH_GRANT
     *
     * @mbg.generated
     */
    public String getIsPovertyHighGrant() {
        return isPovertyHighGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_POVERTY_HIGH_GRANT
     *
     * @param isPovertyHighGrant the value for TBL_EDUCATION.IS_POVERTY_HIGH_GRANT
     *
     * @mbg.generated
     */
    public void setIsPovertyHighGrant(String isPovertyHighGrant) {
        this.isPovertyHighGrant = isPovertyHighGrant == null ? null : isPovertyHighGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_NUTRITION_PLAN
     *
     * @return the value of TBL_EDUCATION.IS_NUTRITION_PLAN
     *
     * @mbg.generated
     */
    public String getIsNutritionPlan() {
        return isNutritionPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_NUTRITION_PLAN
     *
     * @param isNutritionPlan the value for TBL_EDUCATION.IS_NUTRITION_PLAN
     *
     * @mbg.generated
     */
    public void setIsNutritionPlan(String isNutritionPlan) {
        this.isNutritionPlan = isNutritionPlan == null ? null : isNutritionPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.IS_INSURANCE_PREMIUMS
     *
     * @return the value of TBL_EDUCATION.IS_INSURANCE_PREMIUMS
     *
     * @mbg.generated
     */
    public String getIsInsurancePremiums() {
        return isInsurancePremiums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.IS_INSURANCE_PREMIUMS
     *
     * @param isInsurancePremiums the value for TBL_EDUCATION.IS_INSURANCE_PREMIUMS
     *
     * @mbg.generated
     */
    public void setIsInsurancePremiums(String isInsurancePremiums) {
        this.isInsurancePremiums = isInsurancePremiums == null ? null : isInsurancePremiums.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.OTHERS
     *
     * @return the value of TBL_EDUCATION.OTHERS
     *
     * @mbg.generated
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.OTHERS
     *
     * @param others the value for TBL_EDUCATION.OTHERS
     *
     * @mbg.generated
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EDUCATION.ZONE_YEAR
     *
     * @return the value of TBL_EDUCATION.ZONE_YEAR
     *
     * @mbg.generated
     */
    public Long getZoneYear() {
        return zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EDUCATION.ZONE_YEAR
     *
     * @param zoneYear the value for TBL_EDUCATION.ZONE_YEAR
     *
     * @mbg.generated
     */
    public void setZoneYear(Long zoneYear) {
        this.zoneYear = zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EducationDD other = (EducationDD) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getTownName() == null ? other.getTownName() == null : this.getTownName().equals(other.getTownName()))
            && (this.getVillageName() == null ? other.getVillageName() == null : this.getVillageName().equals(other.getVillageName()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getIsDropSchool() == null ? other.getIsDropSchool() == null : this.getIsDropSchool().equals(other.getIsDropSchool()))
            && (this.getStudyGrade() == null ? other.getStudyGrade() == null : this.getStudyGrade().equals(other.getStudyGrade()))
            && (this.getStudySchoolName() == null ? other.getStudySchoolName() == null : this.getStudySchoolName().equals(other.getStudySchoolName()))
            && (this.getIsTeaching() == null ? other.getIsTeaching() == null : this.getIsTeaching().equals(other.getIsTeaching()))
            && (this.getIsAttendant() == null ? other.getIsAttendant() == null : this.getIsAttendant().equals(other.getIsAttendant()))
            && (this.getIsSpecialEducation() == null ? other.getIsSpecialEducation() == null : this.getIsSpecialEducation().equals(other.getIsSpecialEducation()))
            && (this.getIsInfantSubsidy() == null ? other.getIsInfantSubsidy() == null : this.getIsInfantSubsidy().equals(other.getIsInfantSubsidy()))
            && (this.getIsBoardingStudents() == null ? other.getIsBoardingStudents() == null : this.getIsBoardingStudents().equals(other.getIsBoardingStudents()))
            && (this.getIsHighSchGrant() == null ? other.getIsHighSchGrant() == null : this.getIsHighSchGrant().equals(other.getIsHighSchGrant()))
            && (this.getIsScondarySchGrant() == null ? other.getIsScondarySchGrant() == null : this.getIsScondarySchGrant().equals(other.getIsScondarySchGrant()))
            && (this.getIsScondarySchTuition() == null ? other.getIsScondarySchTuition() == null : this.getIsScondarySchTuition().equals(other.getIsScondarySchTuition()))
            && (this.getIsPovertyScondaryGrant() == null ? other.getIsPovertyScondaryGrant() == null : this.getIsPovertyScondaryGrant().equals(other.getIsPovertyScondaryGrant()))
            && (this.getIsPovertyHighGrant() == null ? other.getIsPovertyHighGrant() == null : this.getIsPovertyHighGrant().equals(other.getIsPovertyHighGrant()))
            && (this.getIsNutritionPlan() == null ? other.getIsNutritionPlan() == null : this.getIsNutritionPlan().equals(other.getIsNutritionPlan()))
            && (this.getIsInsurancePremiums() == null ? other.getIsInsurancePremiums() == null : this.getIsInsurancePremiums().equals(other.getIsInsurancePremiums()))
            && (this.getOthers() == null ? other.getOthers() == null : this.getOthers().equals(other.getOthers()))
            && (this.getZoneYear() == null ? other.getZoneYear() == null : this.getZoneYear().equals(other.getZoneYear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getTownName() == null) ? 0 : getTownName().hashCode());
        result = prime * result + ((getVillageName() == null) ? 0 : getVillageName().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getIsDropSchool() == null) ? 0 : getIsDropSchool().hashCode());
        result = prime * result + ((getStudyGrade() == null) ? 0 : getStudyGrade().hashCode());
        result = prime * result + ((getStudySchoolName() == null) ? 0 : getStudySchoolName().hashCode());
        result = prime * result + ((getIsTeaching() == null) ? 0 : getIsTeaching().hashCode());
        result = prime * result + ((getIsAttendant() == null) ? 0 : getIsAttendant().hashCode());
        result = prime * result + ((getIsSpecialEducation() == null) ? 0 : getIsSpecialEducation().hashCode());
        result = prime * result + ((getIsInfantSubsidy() == null) ? 0 : getIsInfantSubsidy().hashCode());
        result = prime * result + ((getIsBoardingStudents() == null) ? 0 : getIsBoardingStudents().hashCode());
        result = prime * result + ((getIsHighSchGrant() == null) ? 0 : getIsHighSchGrant().hashCode());
        result = prime * result + ((getIsScondarySchGrant() == null) ? 0 : getIsScondarySchGrant().hashCode());
        result = prime * result + ((getIsScondarySchTuition() == null) ? 0 : getIsScondarySchTuition().hashCode());
        result = prime * result + ((getIsPovertyScondaryGrant() == null) ? 0 : getIsPovertyScondaryGrant().hashCode());
        result = prime * result + ((getIsPovertyHighGrant() == null) ? 0 : getIsPovertyHighGrant().hashCode());
        result = prime * result + ((getIsNutritionPlan() == null) ? 0 : getIsNutritionPlan().hashCode());
        result = prime * result + ((getIsInsurancePremiums() == null) ? 0 : getIsInsurancePremiums().hashCode());
        result = prime * result + ((getOthers() == null) ? 0 : getOthers().hashCode());
        result = prime * result + ((getZoneYear() == null) ? 0 : getZoneYear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EDUCATION
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", districtName=").append(districtName);
        sb.append(", townName=").append(townName);
        sb.append(", villageName=").append(villageName);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", isDropSchool=").append(isDropSchool);
        sb.append(", studyGrade=").append(studyGrade);
        sb.append(", studySchoolName=").append(studySchoolName);
        sb.append(", isTeaching=").append(isTeaching);
        sb.append(", isAttendant=").append(isAttendant);
        sb.append(", isSpecialEducation=").append(isSpecialEducation);
        sb.append(", isInfantSubsidy=").append(isInfantSubsidy);
        sb.append(", isBoardingStudents=").append(isBoardingStudents);
        sb.append(", isHighSchGrant=").append(isHighSchGrant);
        sb.append(", isScondarySchGrant=").append(isScondarySchGrant);
        sb.append(", isScondarySchTuition=").append(isScondarySchTuition);
        sb.append(", isPovertyScondaryGrant=").append(isPovertyScondaryGrant);
        sb.append(", isPovertyHighGrant=").append(isPovertyHighGrant);
        sb.append(", isNutritionPlan=").append(isNutritionPlan);
        sb.append(", isInsurancePremiums=").append(isInsurancePremiums);
        sb.append(", others=").append(others);
        sb.append(", zoneYear=").append(zoneYear);
        sb.append("]");
        return sb.toString();
    }
}