package com.sysh.entity.helpmea;

import java.io.Serializable;
import java.math.BigDecimal;

public class EmploymentDD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.EMPLOY_NAME
     *
     * @mbg.generated
     */
    private String employName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.ID_NUMBER
     *
     * @mbg.generated
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.REGISTERED_RESIDENCE
     *
     * @mbg.generated
     */
    private String registeredResidence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.SEX
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.AGE
     *
     * @mbg.generated
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.NATION
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.POLITICAL_OUTLOOK
     *
     * @mbg.generated
     */
    private String politicalOutlook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.DEGREE_EDUCATION
     *
     * @mbg.generated
     */
    private String degreeEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.HEALTH
     *
     * @mbg.generated
     */
    private String health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.LABOR_SKILLS
     *
     * @mbg.generated
     */
    private String laborSkills;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.POVERTY_NAME
     *
     * @mbg.generated
     */
    private String povertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.MAJORCAUSE
     *
     * @mbg.generated
     */
    private String majorcause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.IS_STUDENT
     *
     * @mbg.generated
     */
    private String isStudent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.FORM_EMPLOYMENT
     *
     * @mbg.generated
     */
    private String formEmployment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.REGION_EMPLOYMENT
     *
     * @mbg.generated
     */
    private String regionEmployment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.PLACE_EMPLOYMENT
     *
     * @mbg.generated
     */
    private String placeEmployment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.EMPLOYMENT_WORK
     *
     * @mbg.generated
     */
    private String employmentWork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.EMPLOYMENT_TIME
     *
     * @mbg.generated
     */
    private String employmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.SIGNCONTRACT
     *
     * @mbg.generated
     */
    private String signcontract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.IS_SOCIAL_INSURANCE
     *
     * @mbg.generated
     */
    private String isSocialInsurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.MONTHLY_AVERAGE_WAGE
     *
     * @mbg.generated
     */
    private BigDecimal monthlyAverageWage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.POST_TYPE
     *
     * @mbg.generated
     */
    private String postType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.POST_ADDRESS
     *
     * @mbg.generated
     */
    private String postAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.POST_TYPE_COMPANY
     *
     * @mbg.generated
     */
    private String postTypeCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.RESETTLEMENT_TIME
     *
     * @mbg.generated
     */
    private String resettlementTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.POST_NAME
     *
     * @mbg.generated
     */
    private String postName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.VOCATIONAL_TRAINING
     *
     * @mbg.generated
     */
    private String vocationalTraining;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.TRAIN_TYPE
     *
     * @mbg.generated
     */
    private String trainType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.TRAIN_START_TIME
     *
     * @mbg.generated
     */
    private String trainStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.TRAIN_STOP_TIME
     *
     * @mbg.generated
     */
    private String trainStopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.TRAINING_CATEGORY
     *
     * @mbg.generated
     */
    private String trainingCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.OBTAIN_A_CERTIFICATE
     *
     * @mbg.generated
     */
    private String obtainACertificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.TRAINING_SUBSIDY
     *
     * @mbg.generated
     */
    private BigDecimal trainingSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.IS_OBTAIN_EMPLOYMENT
     *
     * @mbg.generated
     */
    private String isObtainEmployment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.START_TIME
     *
     * @mbg.generated
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.IS_TRAIN_ENTREPRENEURSHIP
     *
     * @mbg.generated
     */
    private String isTrainEntrepreneurship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_TYPE
     *
     * @mbg.generated
     */
    private String entrepreneurshipType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_ADDRESS
     *
     * @mbg.generated
     */
    private String entrepreneurshipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_NAME
     *
     * @mbg.generated
     */
    private String entrepreneurshipName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.INDUSTRY_CATEGORY
     *
     * @mbg.generated
     */
    private String industryCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.IS_MICROFINANCE
     *
     * @mbg.generated
     */
    private String isMicrofinance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal loanAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.LABOR_FORCE
     *
     * @mbg.generated
     */
    private Long laborForce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.IS_REGISTER
     *
     * @mbg.generated
     */
    private String isRegister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.IS_EMPLOYMENT_DESIRE
     *
     * @mbg.generated
     */
    private String isEmploymentDesire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.EMPLOYMENT_INTENTION
     *
     * @mbg.generated
     */
    private String employmentIntention;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.SALARY_EXPECTATION
     *
     * @mbg.generated
     */
    private BigDecimal salaryExpectation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.EMPLOYMENT_SERVICE_DEMAND
     *
     * @mbg.generated
     */
    private String employmentServiceDemand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.EMPLOYMENT_CONSULTATION
     *
     * @mbg.generated
     */
    private Long employmentConsultation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.EMPLOYMENT_INFO
     *
     * @mbg.generated
     */
    private Long employmentInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.EMPLOYMENT_GUIDANCE
     *
     * @mbg.generated
     */
    private Long employmentGuidance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.NUMBER_OF_TRAINING
     *
     * @mbg.generated
     */
    private Long numberOfTraining;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.ENTREPRENEURIAL_SERVICE
     *
     * @mbg.generated
     */
    private Long entrepreneurialService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.CAREER_INTRODUCTION
     *
     * @mbg.generated
     */
    private String careerIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.SOCIAL_INSURANCE
     *
     * @mbg.generated
     */
    private String socialInsurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.ENJOY_POST_SUBSIDIES
     *
     * @mbg.generated
     */
    private String enjoyPostSubsidies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.OTHER_POLICIES
     *
     * @mbg.generated
     */
    private String otherPolicies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMPLOYMENT.ZONE_YEAR
     *
     * @mbg.generated
     */
    private Long zoneYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.ID
     *
     * @return the value of TBL_EMPLOYMENT.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.ID
     *
     * @param id the value for TBL_EMPLOYMENT.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.EMPLOY_NAME
     *
     * @return the value of TBL_EMPLOYMENT.EMPLOY_NAME
     *
     * @mbg.generated
     */
    public String getEmployName() {
        return employName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.EMPLOY_NAME
     *
     * @param employName the value for TBL_EMPLOYMENT.EMPLOY_NAME
     *
     * @mbg.generated
     */
    public void setEmployName(String employName) {
        this.employName = employName == null ? null : employName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.ID_NUMBER
     *
     * @return the value of TBL_EMPLOYMENT.ID_NUMBER
     *
     * @mbg.generated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.ID_NUMBER
     *
     * @param idNumber the value for TBL_EMPLOYMENT.ID_NUMBER
     *
     * @mbg.generated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.REGISTERED_RESIDENCE
     *
     * @return the value of TBL_EMPLOYMENT.REGISTERED_RESIDENCE
     *
     * @mbg.generated
     */
    public String getRegisteredResidence() {
        return registeredResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.REGISTERED_RESIDENCE
     *
     * @param registeredResidence the value for TBL_EMPLOYMENT.REGISTERED_RESIDENCE
     *
     * @mbg.generated
     */
    public void setRegisteredResidence(String registeredResidence) {
        this.registeredResidence = registeredResidence == null ? null : registeredResidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.SEX
     *
     * @return the value of TBL_EMPLOYMENT.SEX
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.SEX
     *
     * @param sex the value for TBL_EMPLOYMENT.SEX
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.AGE
     *
     * @return the value of TBL_EMPLOYMENT.AGE
     *
     * @mbg.generated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.AGE
     *
     * @param age the value for TBL_EMPLOYMENT.AGE
     *
     * @mbg.generated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.NATION
     *
     * @return the value of TBL_EMPLOYMENT.NATION
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.NATION
     *
     * @param nation the value for TBL_EMPLOYMENT.NATION
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.POLITICAL_OUTLOOK
     *
     * @return the value of TBL_EMPLOYMENT.POLITICAL_OUTLOOK
     *
     * @mbg.generated
     */
    public String getPoliticalOutlook() {
        return politicalOutlook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.POLITICAL_OUTLOOK
     *
     * @param politicalOutlook the value for TBL_EMPLOYMENT.POLITICAL_OUTLOOK
     *
     * @mbg.generated
     */
    public void setPoliticalOutlook(String politicalOutlook) {
        this.politicalOutlook = politicalOutlook == null ? null : politicalOutlook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.DEGREE_EDUCATION
     *
     * @return the value of TBL_EMPLOYMENT.DEGREE_EDUCATION
     *
     * @mbg.generated
     */
    public String getDegreeEducation() {
        return degreeEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.DEGREE_EDUCATION
     *
     * @param degreeEducation the value for TBL_EMPLOYMENT.DEGREE_EDUCATION
     *
     * @mbg.generated
     */
    public void setDegreeEducation(String degreeEducation) {
        this.degreeEducation = degreeEducation == null ? null : degreeEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.HEALTH
     *
     * @return the value of TBL_EMPLOYMENT.HEALTH
     *
     * @mbg.generated
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.HEALTH
     *
     * @param health the value for TBL_EMPLOYMENT.HEALTH
     *
     * @mbg.generated
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.LABOR_SKILLS
     *
     * @return the value of TBL_EMPLOYMENT.LABOR_SKILLS
     *
     * @mbg.generated
     */
    public String getLaborSkills() {
        return laborSkills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.LABOR_SKILLS
     *
     * @param laborSkills the value for TBL_EMPLOYMENT.LABOR_SKILLS
     *
     * @mbg.generated
     */
    public void setLaborSkills(String laborSkills) {
        this.laborSkills = laborSkills == null ? null : laborSkills.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.POVERTY_NAME
     *
     * @return the value of TBL_EMPLOYMENT.POVERTY_NAME
     *
     * @mbg.generated
     */
    public String getPovertyName() {
        return povertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.POVERTY_NAME
     *
     * @param povertyName the value for TBL_EMPLOYMENT.POVERTY_NAME
     *
     * @mbg.generated
     */
    public void setPovertyName(String povertyName) {
        this.povertyName = povertyName == null ? null : povertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.MAJORCAUSE
     *
     * @return the value of TBL_EMPLOYMENT.MAJORCAUSE
     *
     * @mbg.generated
     */
    public String getMajorcause() {
        return majorcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.MAJORCAUSE
     *
     * @param majorcause the value for TBL_EMPLOYMENT.MAJORCAUSE
     *
     * @mbg.generated
     */
    public void setMajorcause(String majorcause) {
        this.majorcause = majorcause == null ? null : majorcause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.MOBILE
     *
     * @return the value of TBL_EMPLOYMENT.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.MOBILE
     *
     * @param mobile the value for TBL_EMPLOYMENT.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.IS_STUDENT
     *
     * @return the value of TBL_EMPLOYMENT.IS_STUDENT
     *
     * @mbg.generated
     */
    public String getIsStudent() {
        return isStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.IS_STUDENT
     *
     * @param isStudent the value for TBL_EMPLOYMENT.IS_STUDENT
     *
     * @mbg.generated
     */
    public void setIsStudent(String isStudent) {
        this.isStudent = isStudent == null ? null : isStudent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.FORM_EMPLOYMENT
     *
     * @return the value of TBL_EMPLOYMENT.FORM_EMPLOYMENT
     *
     * @mbg.generated
     */
    public String getFormEmployment() {
        return formEmployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.FORM_EMPLOYMENT
     *
     * @param formEmployment the value for TBL_EMPLOYMENT.FORM_EMPLOYMENT
     *
     * @mbg.generated
     */
    public void setFormEmployment(String formEmployment) {
        this.formEmployment = formEmployment == null ? null : formEmployment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.REGION_EMPLOYMENT
     *
     * @return the value of TBL_EMPLOYMENT.REGION_EMPLOYMENT
     *
     * @mbg.generated
     */
    public String getRegionEmployment() {
        return regionEmployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.REGION_EMPLOYMENT
     *
     * @param regionEmployment the value for TBL_EMPLOYMENT.REGION_EMPLOYMENT
     *
     * @mbg.generated
     */
    public void setRegionEmployment(String regionEmployment) {
        this.regionEmployment = regionEmployment == null ? null : regionEmployment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.PLACE_EMPLOYMENT
     *
     * @return the value of TBL_EMPLOYMENT.PLACE_EMPLOYMENT
     *
     * @mbg.generated
     */
    public String getPlaceEmployment() {
        return placeEmployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.PLACE_EMPLOYMENT
     *
     * @param placeEmployment the value for TBL_EMPLOYMENT.PLACE_EMPLOYMENT
     *
     * @mbg.generated
     */
    public void setPlaceEmployment(String placeEmployment) {
        this.placeEmployment = placeEmployment == null ? null : placeEmployment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_WORK
     *
     * @return the value of TBL_EMPLOYMENT.EMPLOYMENT_WORK
     *
     * @mbg.generated
     */
    public String getEmploymentWork() {
        return employmentWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_WORK
     *
     * @param employmentWork the value for TBL_EMPLOYMENT.EMPLOYMENT_WORK
     *
     * @mbg.generated
     */
    public void setEmploymentWork(String employmentWork) {
        this.employmentWork = employmentWork == null ? null : employmentWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_TIME
     *
     * @return the value of TBL_EMPLOYMENT.EMPLOYMENT_TIME
     *
     * @mbg.generated
     */
    public String getEmploymentTime() {
        return employmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_TIME
     *
     * @param employmentTime the value for TBL_EMPLOYMENT.EMPLOYMENT_TIME
     *
     * @mbg.generated
     */
    public void setEmploymentTime(String employmentTime) {
        this.employmentTime = employmentTime == null ? null : employmentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.SIGNCONTRACT
     *
     * @return the value of TBL_EMPLOYMENT.SIGNCONTRACT
     *
     * @mbg.generated
     */
    public String getSigncontract() {
        return signcontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.SIGNCONTRACT
     *
     * @param signcontract the value for TBL_EMPLOYMENT.SIGNCONTRACT
     *
     * @mbg.generated
     */
    public void setSigncontract(String signcontract) {
        this.signcontract = signcontract == null ? null : signcontract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.IS_SOCIAL_INSURANCE
     *
     * @return the value of TBL_EMPLOYMENT.IS_SOCIAL_INSURANCE
     *
     * @mbg.generated
     */
    public String getIsSocialInsurance() {
        return isSocialInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.IS_SOCIAL_INSURANCE
     *
     * @param isSocialInsurance the value for TBL_EMPLOYMENT.IS_SOCIAL_INSURANCE
     *
     * @mbg.generated
     */
    public void setIsSocialInsurance(String isSocialInsurance) {
        this.isSocialInsurance = isSocialInsurance == null ? null : isSocialInsurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.MONTHLY_AVERAGE_WAGE
     *
     * @return the value of TBL_EMPLOYMENT.MONTHLY_AVERAGE_WAGE
     *
     * @mbg.generated
     */
    public BigDecimal getMonthlyAverageWage() {
        return monthlyAverageWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.MONTHLY_AVERAGE_WAGE
     *
     * @param monthlyAverageWage the value for TBL_EMPLOYMENT.MONTHLY_AVERAGE_WAGE
     *
     * @mbg.generated
     */
    public void setMonthlyAverageWage(BigDecimal monthlyAverageWage) {
        this.monthlyAverageWage = monthlyAverageWage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.POST_TYPE
     *
     * @return the value of TBL_EMPLOYMENT.POST_TYPE
     *
     * @mbg.generated
     */
    public String getPostType() {
        return postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.POST_TYPE
     *
     * @param postType the value for TBL_EMPLOYMENT.POST_TYPE
     *
     * @mbg.generated
     */
    public void setPostType(String postType) {
        this.postType = postType == null ? null : postType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.POST_ADDRESS
     *
     * @return the value of TBL_EMPLOYMENT.POST_ADDRESS
     *
     * @mbg.generated
     */
    public String getPostAddress() {
        return postAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.POST_ADDRESS
     *
     * @param postAddress the value for TBL_EMPLOYMENT.POST_ADDRESS
     *
     * @mbg.generated
     */
    public void setPostAddress(String postAddress) {
        this.postAddress = postAddress == null ? null : postAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.POST_TYPE_COMPANY
     *
     * @return the value of TBL_EMPLOYMENT.POST_TYPE_COMPANY
     *
     * @mbg.generated
     */
    public String getPostTypeCompany() {
        return postTypeCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.POST_TYPE_COMPANY
     *
     * @param postTypeCompany the value for TBL_EMPLOYMENT.POST_TYPE_COMPANY
     *
     * @mbg.generated
     */
    public void setPostTypeCompany(String postTypeCompany) {
        this.postTypeCompany = postTypeCompany == null ? null : postTypeCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.RESETTLEMENT_TIME
     *
     * @return the value of TBL_EMPLOYMENT.RESETTLEMENT_TIME
     *
     * @mbg.generated
     */
    public String getResettlementTime() {
        return resettlementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.RESETTLEMENT_TIME
     *
     * @param resettlementTime the value for TBL_EMPLOYMENT.RESETTLEMENT_TIME
     *
     * @mbg.generated
     */
    public void setResettlementTime(String resettlementTime) {
        this.resettlementTime = resettlementTime == null ? null : resettlementTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.POST_NAME
     *
     * @return the value of TBL_EMPLOYMENT.POST_NAME
     *
     * @mbg.generated
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.POST_NAME
     *
     * @param postName the value for TBL_EMPLOYMENT.POST_NAME
     *
     * @mbg.generated
     */
    public void setPostName(String postName) {
        this.postName = postName == null ? null : postName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.VOCATIONAL_TRAINING
     *
     * @return the value of TBL_EMPLOYMENT.VOCATIONAL_TRAINING
     *
     * @mbg.generated
     */
    public String getVocationalTraining() {
        return vocationalTraining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.VOCATIONAL_TRAINING
     *
     * @param vocationalTraining the value for TBL_EMPLOYMENT.VOCATIONAL_TRAINING
     *
     * @mbg.generated
     */
    public void setVocationalTraining(String vocationalTraining) {
        this.vocationalTraining = vocationalTraining == null ? null : vocationalTraining.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.TRAIN_TYPE
     *
     * @return the value of TBL_EMPLOYMENT.TRAIN_TYPE
     *
     * @mbg.generated
     */
    public String getTrainType() {
        return trainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.TRAIN_TYPE
     *
     * @param trainType the value for TBL_EMPLOYMENT.TRAIN_TYPE
     *
     * @mbg.generated
     */
    public void setTrainType(String trainType) {
        this.trainType = trainType == null ? null : trainType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.TRAIN_START_TIME
     *
     * @return the value of TBL_EMPLOYMENT.TRAIN_START_TIME
     *
     * @mbg.generated
     */
    public String getTrainStartTime() {
        return trainStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.TRAIN_START_TIME
     *
     * @param trainStartTime the value for TBL_EMPLOYMENT.TRAIN_START_TIME
     *
     * @mbg.generated
     */
    public void setTrainStartTime(String trainStartTime) {
        this.trainStartTime = trainStartTime == null ? null : trainStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.TRAIN_STOP_TIME
     *
     * @return the value of TBL_EMPLOYMENT.TRAIN_STOP_TIME
     *
     * @mbg.generated
     */
    public String getTrainStopTime() {
        return trainStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.TRAIN_STOP_TIME
     *
     * @param trainStopTime the value for TBL_EMPLOYMENT.TRAIN_STOP_TIME
     *
     * @mbg.generated
     */
    public void setTrainStopTime(String trainStopTime) {
        this.trainStopTime = trainStopTime == null ? null : trainStopTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.TRAINING_CATEGORY
     *
     * @return the value of TBL_EMPLOYMENT.TRAINING_CATEGORY
     *
     * @mbg.generated
     */
    public String getTrainingCategory() {
        return trainingCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.TRAINING_CATEGORY
     *
     * @param trainingCategory the value for TBL_EMPLOYMENT.TRAINING_CATEGORY
     *
     * @mbg.generated
     */
    public void setTrainingCategory(String trainingCategory) {
        this.trainingCategory = trainingCategory == null ? null : trainingCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.OBTAIN_A_CERTIFICATE
     *
     * @return the value of TBL_EMPLOYMENT.OBTAIN_A_CERTIFICATE
     *
     * @mbg.generated
     */
    public String getObtainACertificate() {
        return obtainACertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.OBTAIN_A_CERTIFICATE
     *
     * @param obtainACertificate the value for TBL_EMPLOYMENT.OBTAIN_A_CERTIFICATE
     *
     * @mbg.generated
     */
    public void setObtainACertificate(String obtainACertificate) {
        this.obtainACertificate = obtainACertificate == null ? null : obtainACertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.TRAINING_SUBSIDY
     *
     * @return the value of TBL_EMPLOYMENT.TRAINING_SUBSIDY
     *
     * @mbg.generated
     */
    public BigDecimal getTrainingSubsidy() {
        return trainingSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.TRAINING_SUBSIDY
     *
     * @param trainingSubsidy the value for TBL_EMPLOYMENT.TRAINING_SUBSIDY
     *
     * @mbg.generated
     */
    public void setTrainingSubsidy(BigDecimal trainingSubsidy) {
        this.trainingSubsidy = trainingSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.IS_OBTAIN_EMPLOYMENT
     *
     * @return the value of TBL_EMPLOYMENT.IS_OBTAIN_EMPLOYMENT
     *
     * @mbg.generated
     */
    public String getIsObtainEmployment() {
        return isObtainEmployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.IS_OBTAIN_EMPLOYMENT
     *
     * @param isObtainEmployment the value for TBL_EMPLOYMENT.IS_OBTAIN_EMPLOYMENT
     *
     * @mbg.generated
     */
    public void setIsObtainEmployment(String isObtainEmployment) {
        this.isObtainEmployment = isObtainEmployment == null ? null : isObtainEmployment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.START_TIME
     *
     * @return the value of TBL_EMPLOYMENT.START_TIME
     *
     * @mbg.generated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.START_TIME
     *
     * @param startTime the value for TBL_EMPLOYMENT.START_TIME
     *
     * @mbg.generated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.IS_TRAIN_ENTREPRENEURSHIP
     *
     * @return the value of TBL_EMPLOYMENT.IS_TRAIN_ENTREPRENEURSHIP
     *
     * @mbg.generated
     */
    public String getIsTrainEntrepreneurship() {
        return isTrainEntrepreneurship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.IS_TRAIN_ENTREPRENEURSHIP
     *
     * @param isTrainEntrepreneurship the value for TBL_EMPLOYMENT.IS_TRAIN_ENTREPRENEURSHIP
     *
     * @mbg.generated
     */
    public void setIsTrainEntrepreneurship(String isTrainEntrepreneurship) {
        this.isTrainEntrepreneurship = isTrainEntrepreneurship == null ? null : isTrainEntrepreneurship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_TYPE
     *
     * @return the value of TBL_EMPLOYMENT.ENTREPRENEURSHIP_TYPE
     *
     * @mbg.generated
     */
    public String getEntrepreneurshipType() {
        return entrepreneurshipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_TYPE
     *
     * @param entrepreneurshipType the value for TBL_EMPLOYMENT.ENTREPRENEURSHIP_TYPE
     *
     * @mbg.generated
     */
    public void setEntrepreneurshipType(String entrepreneurshipType) {
        this.entrepreneurshipType = entrepreneurshipType == null ? null : entrepreneurshipType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_ADDRESS
     *
     * @return the value of TBL_EMPLOYMENT.ENTREPRENEURSHIP_ADDRESS
     *
     * @mbg.generated
     */
    public String getEntrepreneurshipAddress() {
        return entrepreneurshipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_ADDRESS
     *
     * @param entrepreneurshipAddress the value for TBL_EMPLOYMENT.ENTREPRENEURSHIP_ADDRESS
     *
     * @mbg.generated
     */
    public void setEntrepreneurshipAddress(String entrepreneurshipAddress) {
        this.entrepreneurshipAddress = entrepreneurshipAddress == null ? null : entrepreneurshipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_NAME
     *
     * @return the value of TBL_EMPLOYMENT.ENTREPRENEURSHIP_NAME
     *
     * @mbg.generated
     */
    public String getEntrepreneurshipName() {
        return entrepreneurshipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.ENTREPRENEURSHIP_NAME
     *
     * @param entrepreneurshipName the value for TBL_EMPLOYMENT.ENTREPRENEURSHIP_NAME
     *
     * @mbg.generated
     */
    public void setEntrepreneurshipName(String entrepreneurshipName) {
        this.entrepreneurshipName = entrepreneurshipName == null ? null : entrepreneurshipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.INDUSTRY_CATEGORY
     *
     * @return the value of TBL_EMPLOYMENT.INDUSTRY_CATEGORY
     *
     * @mbg.generated
     */
    public String getIndustryCategory() {
        return industryCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.INDUSTRY_CATEGORY
     *
     * @param industryCategory the value for TBL_EMPLOYMENT.INDUSTRY_CATEGORY
     *
     * @mbg.generated
     */
    public void setIndustryCategory(String industryCategory) {
        this.industryCategory = industryCategory == null ? null : industryCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.IS_MICROFINANCE
     *
     * @return the value of TBL_EMPLOYMENT.IS_MICROFINANCE
     *
     * @mbg.generated
     */
    public String getIsMicrofinance() {
        return isMicrofinance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.IS_MICROFINANCE
     *
     * @param isMicrofinance the value for TBL_EMPLOYMENT.IS_MICROFINANCE
     *
     * @mbg.generated
     */
    public void setIsMicrofinance(String isMicrofinance) {
        this.isMicrofinance = isMicrofinance == null ? null : isMicrofinance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.LOAN_AMOUNT
     *
     * @return the value of TBL_EMPLOYMENT.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.LOAN_AMOUNT
     *
     * @param loanAmount the value for TBL_EMPLOYMENT.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.LABOR_FORCE
     *
     * @return the value of TBL_EMPLOYMENT.LABOR_FORCE
     *
     * @mbg.generated
     */
    public Long getLaborForce() {
        return laborForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.LABOR_FORCE
     *
     * @param laborForce the value for TBL_EMPLOYMENT.LABOR_FORCE
     *
     * @mbg.generated
     */
    public void setLaborForce(Long laborForce) {
        this.laborForce = laborForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.IS_REGISTER
     *
     * @return the value of TBL_EMPLOYMENT.IS_REGISTER
     *
     * @mbg.generated
     */
    public String getIsRegister() {
        return isRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.IS_REGISTER
     *
     * @param isRegister the value for TBL_EMPLOYMENT.IS_REGISTER
     *
     * @mbg.generated
     */
    public void setIsRegister(String isRegister) {
        this.isRegister = isRegister == null ? null : isRegister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.IS_EMPLOYMENT_DESIRE
     *
     * @return the value of TBL_EMPLOYMENT.IS_EMPLOYMENT_DESIRE
     *
     * @mbg.generated
     */
    public String getIsEmploymentDesire() {
        return isEmploymentDesire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.IS_EMPLOYMENT_DESIRE
     *
     * @param isEmploymentDesire the value for TBL_EMPLOYMENT.IS_EMPLOYMENT_DESIRE
     *
     * @mbg.generated
     */
    public void setIsEmploymentDesire(String isEmploymentDesire) {
        this.isEmploymentDesire = isEmploymentDesire == null ? null : isEmploymentDesire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_INTENTION
     *
     * @return the value of TBL_EMPLOYMENT.EMPLOYMENT_INTENTION
     *
     * @mbg.generated
     */
    public String getEmploymentIntention() {
        return employmentIntention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_INTENTION
     *
     * @param employmentIntention the value for TBL_EMPLOYMENT.EMPLOYMENT_INTENTION
     *
     * @mbg.generated
     */
    public void setEmploymentIntention(String employmentIntention) {
        this.employmentIntention = employmentIntention == null ? null : employmentIntention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.SALARY_EXPECTATION
     *
     * @return the value of TBL_EMPLOYMENT.SALARY_EXPECTATION
     *
     * @mbg.generated
     */
    public BigDecimal getSalaryExpectation() {
        return salaryExpectation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.SALARY_EXPECTATION
     *
     * @param salaryExpectation the value for TBL_EMPLOYMENT.SALARY_EXPECTATION
     *
     * @mbg.generated
     */
    public void setSalaryExpectation(BigDecimal salaryExpectation) {
        this.salaryExpectation = salaryExpectation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_SERVICE_DEMAND
     *
     * @return the value of TBL_EMPLOYMENT.EMPLOYMENT_SERVICE_DEMAND
     *
     * @mbg.generated
     */
    public String getEmploymentServiceDemand() {
        return employmentServiceDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_SERVICE_DEMAND
     *
     * @param employmentServiceDemand the value for TBL_EMPLOYMENT.EMPLOYMENT_SERVICE_DEMAND
     *
     * @mbg.generated
     */
    public void setEmploymentServiceDemand(String employmentServiceDemand) {
        this.employmentServiceDemand = employmentServiceDemand == null ? null : employmentServiceDemand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_CONSULTATION
     *
     * @return the value of TBL_EMPLOYMENT.EMPLOYMENT_CONSULTATION
     *
     * @mbg.generated
     */
    public Long getEmploymentConsultation() {
        return employmentConsultation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_CONSULTATION
     *
     * @param employmentConsultation the value for TBL_EMPLOYMENT.EMPLOYMENT_CONSULTATION
     *
     * @mbg.generated
     */
    public void setEmploymentConsultation(Long employmentConsultation) {
        this.employmentConsultation = employmentConsultation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_INFO
     *
     * @return the value of TBL_EMPLOYMENT.EMPLOYMENT_INFO
     *
     * @mbg.generated
     */
    public Long getEmploymentInfo() {
        return employmentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_INFO
     *
     * @param employmentInfo the value for TBL_EMPLOYMENT.EMPLOYMENT_INFO
     *
     * @mbg.generated
     */
    public void setEmploymentInfo(Long employmentInfo) {
        this.employmentInfo = employmentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_GUIDANCE
     *
     * @return the value of TBL_EMPLOYMENT.EMPLOYMENT_GUIDANCE
     *
     * @mbg.generated
     */
    public Long getEmploymentGuidance() {
        return employmentGuidance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.EMPLOYMENT_GUIDANCE
     *
     * @param employmentGuidance the value for TBL_EMPLOYMENT.EMPLOYMENT_GUIDANCE
     *
     * @mbg.generated
     */
    public void setEmploymentGuidance(Long employmentGuidance) {
        this.employmentGuidance = employmentGuidance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.NUMBER_OF_TRAINING
     *
     * @return the value of TBL_EMPLOYMENT.NUMBER_OF_TRAINING
     *
     * @mbg.generated
     */
    public Long getNumberOfTraining() {
        return numberOfTraining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.NUMBER_OF_TRAINING
     *
     * @param numberOfTraining the value for TBL_EMPLOYMENT.NUMBER_OF_TRAINING
     *
     * @mbg.generated
     */
    public void setNumberOfTraining(Long numberOfTraining) {
        this.numberOfTraining = numberOfTraining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.ENTREPRENEURIAL_SERVICE
     *
     * @return the value of TBL_EMPLOYMENT.ENTREPRENEURIAL_SERVICE
     *
     * @mbg.generated
     */
    public Long getEntrepreneurialService() {
        return entrepreneurialService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.ENTREPRENEURIAL_SERVICE
     *
     * @param entrepreneurialService the value for TBL_EMPLOYMENT.ENTREPRENEURIAL_SERVICE
     *
     * @mbg.generated
     */
    public void setEntrepreneurialService(Long entrepreneurialService) {
        this.entrepreneurialService = entrepreneurialService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.CAREER_INTRODUCTION
     *
     * @return the value of TBL_EMPLOYMENT.CAREER_INTRODUCTION
     *
     * @mbg.generated
     */
    public String getCareerIntroduction() {
        return careerIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.CAREER_INTRODUCTION
     *
     * @param careerIntroduction the value for TBL_EMPLOYMENT.CAREER_INTRODUCTION
     *
     * @mbg.generated
     */
    public void setCareerIntroduction(String careerIntroduction) {
        this.careerIntroduction = careerIntroduction == null ? null : careerIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.SOCIAL_INSURANCE
     *
     * @return the value of TBL_EMPLOYMENT.SOCIAL_INSURANCE
     *
     * @mbg.generated
     */
    public String getSocialInsurance() {
        return socialInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.SOCIAL_INSURANCE
     *
     * @param socialInsurance the value for TBL_EMPLOYMENT.SOCIAL_INSURANCE
     *
     * @mbg.generated
     */
    public void setSocialInsurance(String socialInsurance) {
        this.socialInsurance = socialInsurance == null ? null : socialInsurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.ENJOY_POST_SUBSIDIES
     *
     * @return the value of TBL_EMPLOYMENT.ENJOY_POST_SUBSIDIES
     *
     * @mbg.generated
     */
    public String getEnjoyPostSubsidies() {
        return enjoyPostSubsidies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.ENJOY_POST_SUBSIDIES
     *
     * @param enjoyPostSubsidies the value for TBL_EMPLOYMENT.ENJOY_POST_SUBSIDIES
     *
     * @mbg.generated
     */
    public void setEnjoyPostSubsidies(String enjoyPostSubsidies) {
        this.enjoyPostSubsidies = enjoyPostSubsidies == null ? null : enjoyPostSubsidies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.OTHER_POLICIES
     *
     * @return the value of TBL_EMPLOYMENT.OTHER_POLICIES
     *
     * @mbg.generated
     */
    public String getOtherPolicies() {
        return otherPolicies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.OTHER_POLICIES
     *
     * @param otherPolicies the value for TBL_EMPLOYMENT.OTHER_POLICIES
     *
     * @mbg.generated
     */
    public void setOtherPolicies(String otherPolicies) {
        this.otherPolicies = otherPolicies == null ? null : otherPolicies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMPLOYMENT.ZONE_YEAR
     *
     * @return the value of TBL_EMPLOYMENT.ZONE_YEAR
     *
     * @mbg.generated
     */
    public Long getZoneYear() {
        return zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMPLOYMENT.ZONE_YEAR
     *
     * @param zoneYear the value for TBL_EMPLOYMENT.ZONE_YEAR
     *
     * @mbg.generated
     */
    public void setZoneYear(Long zoneYear) {
        this.zoneYear = zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EmploymentDD other = (EmploymentDD) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmployName() == null ? other.getEmployName() == null : this.getEmployName().equals(other.getEmployName()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getRegisteredResidence() == null ? other.getRegisteredResidence() == null : this.getRegisteredResidence().equals(other.getRegisteredResidence()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getNation() == null ? other.getNation() == null : this.getNation().equals(other.getNation()))
            && (this.getPoliticalOutlook() == null ? other.getPoliticalOutlook() == null : this.getPoliticalOutlook().equals(other.getPoliticalOutlook()))
            && (this.getDegreeEducation() == null ? other.getDegreeEducation() == null : this.getDegreeEducation().equals(other.getDegreeEducation()))
            && (this.getHealth() == null ? other.getHealth() == null : this.getHealth().equals(other.getHealth()))
            && (this.getLaborSkills() == null ? other.getLaborSkills() == null : this.getLaborSkills().equals(other.getLaborSkills()))
            && (this.getPovertyName() == null ? other.getPovertyName() == null : this.getPovertyName().equals(other.getPovertyName()))
            && (this.getMajorcause() == null ? other.getMajorcause() == null : this.getMajorcause().equals(other.getMajorcause()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getIsStudent() == null ? other.getIsStudent() == null : this.getIsStudent().equals(other.getIsStudent()))
            && (this.getFormEmployment() == null ? other.getFormEmployment() == null : this.getFormEmployment().equals(other.getFormEmployment()))
            && (this.getRegionEmployment() == null ? other.getRegionEmployment() == null : this.getRegionEmployment().equals(other.getRegionEmployment()))
            && (this.getPlaceEmployment() == null ? other.getPlaceEmployment() == null : this.getPlaceEmployment().equals(other.getPlaceEmployment()))
            && (this.getEmploymentWork() == null ? other.getEmploymentWork() == null : this.getEmploymentWork().equals(other.getEmploymentWork()))
            && (this.getEmploymentTime() == null ? other.getEmploymentTime() == null : this.getEmploymentTime().equals(other.getEmploymentTime()))
            && (this.getSigncontract() == null ? other.getSigncontract() == null : this.getSigncontract().equals(other.getSigncontract()))
            && (this.getIsSocialInsurance() == null ? other.getIsSocialInsurance() == null : this.getIsSocialInsurance().equals(other.getIsSocialInsurance()))
            && (this.getMonthlyAverageWage() == null ? other.getMonthlyAverageWage() == null : this.getMonthlyAverageWage().equals(other.getMonthlyAverageWage()))
            && (this.getPostType() == null ? other.getPostType() == null : this.getPostType().equals(other.getPostType()))
            && (this.getPostAddress() == null ? other.getPostAddress() == null : this.getPostAddress().equals(other.getPostAddress()))
            && (this.getPostTypeCompany() == null ? other.getPostTypeCompany() == null : this.getPostTypeCompany().equals(other.getPostTypeCompany()))
            && (this.getResettlementTime() == null ? other.getResettlementTime() == null : this.getResettlementTime().equals(other.getResettlementTime()))
            && (this.getPostName() == null ? other.getPostName() == null : this.getPostName().equals(other.getPostName()))
            && (this.getVocationalTraining() == null ? other.getVocationalTraining() == null : this.getVocationalTraining().equals(other.getVocationalTraining()))
            && (this.getTrainType() == null ? other.getTrainType() == null : this.getTrainType().equals(other.getTrainType()))
            && (this.getTrainStartTime() == null ? other.getTrainStartTime() == null : this.getTrainStartTime().equals(other.getTrainStartTime()))
            && (this.getTrainStopTime() == null ? other.getTrainStopTime() == null : this.getTrainStopTime().equals(other.getTrainStopTime()))
            && (this.getTrainingCategory() == null ? other.getTrainingCategory() == null : this.getTrainingCategory().equals(other.getTrainingCategory()))
            && (this.getObtainACertificate() == null ? other.getObtainACertificate() == null : this.getObtainACertificate().equals(other.getObtainACertificate()))
            && (this.getTrainingSubsidy() == null ? other.getTrainingSubsidy() == null : this.getTrainingSubsidy().equals(other.getTrainingSubsidy()))
            && (this.getIsObtainEmployment() == null ? other.getIsObtainEmployment() == null : this.getIsObtainEmployment().equals(other.getIsObtainEmployment()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getIsTrainEntrepreneurship() == null ? other.getIsTrainEntrepreneurship() == null : this.getIsTrainEntrepreneurship().equals(other.getIsTrainEntrepreneurship()))
            && (this.getEntrepreneurshipType() == null ? other.getEntrepreneurshipType() == null : this.getEntrepreneurshipType().equals(other.getEntrepreneurshipType()))
            && (this.getEntrepreneurshipAddress() == null ? other.getEntrepreneurshipAddress() == null : this.getEntrepreneurshipAddress().equals(other.getEntrepreneurshipAddress()))
            && (this.getEntrepreneurshipName() == null ? other.getEntrepreneurshipName() == null : this.getEntrepreneurshipName().equals(other.getEntrepreneurshipName()))
            && (this.getIndustryCategory() == null ? other.getIndustryCategory() == null : this.getIndustryCategory().equals(other.getIndustryCategory()))
            && (this.getIsMicrofinance() == null ? other.getIsMicrofinance() == null : this.getIsMicrofinance().equals(other.getIsMicrofinance()))
            && (this.getLoanAmount() == null ? other.getLoanAmount() == null : this.getLoanAmount().equals(other.getLoanAmount()))
            && (this.getLaborForce() == null ? other.getLaborForce() == null : this.getLaborForce().equals(other.getLaborForce()))
            && (this.getIsRegister() == null ? other.getIsRegister() == null : this.getIsRegister().equals(other.getIsRegister()))
            && (this.getIsEmploymentDesire() == null ? other.getIsEmploymentDesire() == null : this.getIsEmploymentDesire().equals(other.getIsEmploymentDesire()))
            && (this.getEmploymentIntention() == null ? other.getEmploymentIntention() == null : this.getEmploymentIntention().equals(other.getEmploymentIntention()))
            && (this.getSalaryExpectation() == null ? other.getSalaryExpectation() == null : this.getSalaryExpectation().equals(other.getSalaryExpectation()))
            && (this.getEmploymentServiceDemand() == null ? other.getEmploymentServiceDemand() == null : this.getEmploymentServiceDemand().equals(other.getEmploymentServiceDemand()))
            && (this.getEmploymentConsultation() == null ? other.getEmploymentConsultation() == null : this.getEmploymentConsultation().equals(other.getEmploymentConsultation()))
            && (this.getEmploymentInfo() == null ? other.getEmploymentInfo() == null : this.getEmploymentInfo().equals(other.getEmploymentInfo()))
            && (this.getEmploymentGuidance() == null ? other.getEmploymentGuidance() == null : this.getEmploymentGuidance().equals(other.getEmploymentGuidance()))
            && (this.getNumberOfTraining() == null ? other.getNumberOfTraining() == null : this.getNumberOfTraining().equals(other.getNumberOfTraining()))
            && (this.getEntrepreneurialService() == null ? other.getEntrepreneurialService() == null : this.getEntrepreneurialService().equals(other.getEntrepreneurialService()))
            && (this.getCareerIntroduction() == null ? other.getCareerIntroduction() == null : this.getCareerIntroduction().equals(other.getCareerIntroduction()))
            && (this.getSocialInsurance() == null ? other.getSocialInsurance() == null : this.getSocialInsurance().equals(other.getSocialInsurance()))
            && (this.getEnjoyPostSubsidies() == null ? other.getEnjoyPostSubsidies() == null : this.getEnjoyPostSubsidies().equals(other.getEnjoyPostSubsidies()))
            && (this.getOtherPolicies() == null ? other.getOtherPolicies() == null : this.getOtherPolicies().equals(other.getOtherPolicies()))
            && (this.getZoneYear() == null ? other.getZoneYear() == null : this.getZoneYear().equals(other.getZoneYear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmployName() == null) ? 0 : getEmployName().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getRegisteredResidence() == null) ? 0 : getRegisteredResidence().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
        result = prime * result + ((getPoliticalOutlook() == null) ? 0 : getPoliticalOutlook().hashCode());
        result = prime * result + ((getDegreeEducation() == null) ? 0 : getDegreeEducation().hashCode());
        result = prime * result + ((getHealth() == null) ? 0 : getHealth().hashCode());
        result = prime * result + ((getLaborSkills() == null) ? 0 : getLaborSkills().hashCode());
        result = prime * result + ((getPovertyName() == null) ? 0 : getPovertyName().hashCode());
        result = prime * result + ((getMajorcause() == null) ? 0 : getMajorcause().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getIsStudent() == null) ? 0 : getIsStudent().hashCode());
        result = prime * result + ((getFormEmployment() == null) ? 0 : getFormEmployment().hashCode());
        result = prime * result + ((getRegionEmployment() == null) ? 0 : getRegionEmployment().hashCode());
        result = prime * result + ((getPlaceEmployment() == null) ? 0 : getPlaceEmployment().hashCode());
        result = prime * result + ((getEmploymentWork() == null) ? 0 : getEmploymentWork().hashCode());
        result = prime * result + ((getEmploymentTime() == null) ? 0 : getEmploymentTime().hashCode());
        result = prime * result + ((getSigncontract() == null) ? 0 : getSigncontract().hashCode());
        result = prime * result + ((getIsSocialInsurance() == null) ? 0 : getIsSocialInsurance().hashCode());
        result = prime * result + ((getMonthlyAverageWage() == null) ? 0 : getMonthlyAverageWage().hashCode());
        result = prime * result + ((getPostType() == null) ? 0 : getPostType().hashCode());
        result = prime * result + ((getPostAddress() == null) ? 0 : getPostAddress().hashCode());
        result = prime * result + ((getPostTypeCompany() == null) ? 0 : getPostTypeCompany().hashCode());
        result = prime * result + ((getResettlementTime() == null) ? 0 : getResettlementTime().hashCode());
        result = prime * result + ((getPostName() == null) ? 0 : getPostName().hashCode());
        result = prime * result + ((getVocationalTraining() == null) ? 0 : getVocationalTraining().hashCode());
        result = prime * result + ((getTrainType() == null) ? 0 : getTrainType().hashCode());
        result = prime * result + ((getTrainStartTime() == null) ? 0 : getTrainStartTime().hashCode());
        result = prime * result + ((getTrainStopTime() == null) ? 0 : getTrainStopTime().hashCode());
        result = prime * result + ((getTrainingCategory() == null) ? 0 : getTrainingCategory().hashCode());
        result = prime * result + ((getObtainACertificate() == null) ? 0 : getObtainACertificate().hashCode());
        result = prime * result + ((getTrainingSubsidy() == null) ? 0 : getTrainingSubsidy().hashCode());
        result = prime * result + ((getIsObtainEmployment() == null) ? 0 : getIsObtainEmployment().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getIsTrainEntrepreneurship() == null) ? 0 : getIsTrainEntrepreneurship().hashCode());
        result = prime * result + ((getEntrepreneurshipType() == null) ? 0 : getEntrepreneurshipType().hashCode());
        result = prime * result + ((getEntrepreneurshipAddress() == null) ? 0 : getEntrepreneurshipAddress().hashCode());
        result = prime * result + ((getEntrepreneurshipName() == null) ? 0 : getEntrepreneurshipName().hashCode());
        result = prime * result + ((getIndustryCategory() == null) ? 0 : getIndustryCategory().hashCode());
        result = prime * result + ((getIsMicrofinance() == null) ? 0 : getIsMicrofinance().hashCode());
        result = prime * result + ((getLoanAmount() == null) ? 0 : getLoanAmount().hashCode());
        result = prime * result + ((getLaborForce() == null) ? 0 : getLaborForce().hashCode());
        result = prime * result + ((getIsRegister() == null) ? 0 : getIsRegister().hashCode());
        result = prime * result + ((getIsEmploymentDesire() == null) ? 0 : getIsEmploymentDesire().hashCode());
        result = prime * result + ((getEmploymentIntention() == null) ? 0 : getEmploymentIntention().hashCode());
        result = prime * result + ((getSalaryExpectation() == null) ? 0 : getSalaryExpectation().hashCode());
        result = prime * result + ((getEmploymentServiceDemand() == null) ? 0 : getEmploymentServiceDemand().hashCode());
        result = prime * result + ((getEmploymentConsultation() == null) ? 0 : getEmploymentConsultation().hashCode());
        result = prime * result + ((getEmploymentInfo() == null) ? 0 : getEmploymentInfo().hashCode());
        result = prime * result + ((getEmploymentGuidance() == null) ? 0 : getEmploymentGuidance().hashCode());
        result = prime * result + ((getNumberOfTraining() == null) ? 0 : getNumberOfTraining().hashCode());
        result = prime * result + ((getEntrepreneurialService() == null) ? 0 : getEntrepreneurialService().hashCode());
        result = prime * result + ((getCareerIntroduction() == null) ? 0 : getCareerIntroduction().hashCode());
        result = prime * result + ((getSocialInsurance() == null) ? 0 : getSocialInsurance().hashCode());
        result = prime * result + ((getEnjoyPostSubsidies() == null) ? 0 : getEnjoyPostSubsidies().hashCode());
        result = prime * result + ((getOtherPolicies() == null) ? 0 : getOtherPolicies().hashCode());
        result = prime * result + ((getZoneYear() == null) ? 0 : getZoneYear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMPLOYMENT
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", employName=").append(employName);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", registeredResidence=").append(registeredResidence);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", nation=").append(nation);
        sb.append(", politicalOutlook=").append(politicalOutlook);
        sb.append(", degreeEducation=").append(degreeEducation);
        sb.append(", health=").append(health);
        sb.append(", laborSkills=").append(laborSkills);
        sb.append(", povertyName=").append(povertyName);
        sb.append(", majorcause=").append(majorcause);
        sb.append(", mobile=").append(mobile);
        sb.append(", isStudent=").append(isStudent);
        sb.append(", formEmployment=").append(formEmployment);
        sb.append(", regionEmployment=").append(regionEmployment);
        sb.append(", placeEmployment=").append(placeEmployment);
        sb.append(", employmentWork=").append(employmentWork);
        sb.append(", employmentTime=").append(employmentTime);
        sb.append(", signcontract=").append(signcontract);
        sb.append(", isSocialInsurance=").append(isSocialInsurance);
        sb.append(", monthlyAverageWage=").append(monthlyAverageWage);
        sb.append(", postType=").append(postType);
        sb.append(", postAddress=").append(postAddress);
        sb.append(", postTypeCompany=").append(postTypeCompany);
        sb.append(", resettlementTime=").append(resettlementTime);
        sb.append(", postName=").append(postName);
        sb.append(", vocationalTraining=").append(vocationalTraining);
        sb.append(", trainType=").append(trainType);
        sb.append(", trainStartTime=").append(trainStartTime);
        sb.append(", trainStopTime=").append(trainStopTime);
        sb.append(", trainingCategory=").append(trainingCategory);
        sb.append(", obtainACertificate=").append(obtainACertificate);
        sb.append(", trainingSubsidy=").append(trainingSubsidy);
        sb.append(", isObtainEmployment=").append(isObtainEmployment);
        sb.append(", startTime=").append(startTime);
        sb.append(", isTrainEntrepreneurship=").append(isTrainEntrepreneurship);
        sb.append(", entrepreneurshipType=").append(entrepreneurshipType);
        sb.append(", entrepreneurshipAddress=").append(entrepreneurshipAddress);
        sb.append(", entrepreneurshipName=").append(entrepreneurshipName);
        sb.append(", industryCategory=").append(industryCategory);
        sb.append(", isMicrofinance=").append(isMicrofinance);
        sb.append(", loanAmount=").append(loanAmount);
        sb.append(", laborForce=").append(laborForce);
        sb.append(", isRegister=").append(isRegister);
        sb.append(", isEmploymentDesire=").append(isEmploymentDesire);
        sb.append(", employmentIntention=").append(employmentIntention);
        sb.append(", salaryExpectation=").append(salaryExpectation);
        sb.append(", employmentServiceDemand=").append(employmentServiceDemand);
        sb.append(", employmentConsultation=").append(employmentConsultation);
        sb.append(", employmentInfo=").append(employmentInfo);
        sb.append(", employmentGuidance=").append(employmentGuidance);
        sb.append(", numberOfTraining=").append(numberOfTraining);
        sb.append(", entrepreneurialService=").append(entrepreneurialService);
        sb.append(", careerIntroduction=").append(careerIntroduction);
        sb.append(", socialInsurance=").append(socialInsurance);
        sb.append(", enjoyPostSubsidies=").append(enjoyPostSubsidies);
        sb.append(", otherPolicies=").append(otherPolicies);
        sb.append(", zoneYear=").append(zoneYear);
        sb.append("]");
        return sb.toString();
    }
}