package com.sysh.entity.helpmea;

import java.io.Serializable;
import java.math.BigDecimal;

public class IdstProjwayDD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.DISTRICT_NAME
     *
     * @mbg.generated
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.TOWN_NAME
     *
     * @mbg.generated
     */
    private String townName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.VILLAGE_NAME
     *
     * @mbg.generated
     */
    private String villageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.HOLDER_NAME
     *
     * @mbg.generated
     */
    private String holderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.ID_NUMBER
     *
     * @mbg.generated
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.FLOWER_NUM
     *
     * @mbg.generated
     */
    private BigDecimal flowerNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.FLOWER_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal flowerProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.IS_JOIN_TOUR
     *
     * @mbg.generated
     */
    private String isJoinTour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.TOUR_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal tourProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.EC_SCALE
     *
     * @mbg.generated
     */
    private String ecScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.EC_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal ecProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.VEG_NUM
     *
     * @mbg.generated
     */
    private BigDecimal vegNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.VEG_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal vegProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.YANGTAO_NUM
     *
     * @mbg.generated
     */
    private BigDecimal yangtaoNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.YANGTAO_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal yangtaoProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.SHEEP_NUM
     *
     * @mbg.generated
     */
    private BigDecimal sheepNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.SHEEP_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal sheepProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.BEE_NUM
     *
     * @mbg.generated
     */
    private BigDecimal beeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.BEE_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal beeProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.WALNUT_NUM
     *
     * @mbg.generated
     */
    private BigDecimal walnutNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.WALNUT_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal walnutProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.GRAPE_NUM
     *
     * @mbg.generated
     */
    private BigDecimal grapeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.GRAPE_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal grapeProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.GRANADA_NUM
     *
     * @mbg.generated
     */
    private BigDecimal granadaNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.GRANADA_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal granadaProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.OTHERS_NUM
     *
     * @mbg.generated
     */
    private String othersNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.OTHERS_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal othersProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.IS_SKILL_TRAIN
     *
     * @mbg.generated
     */
    private String isSkillTrain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.IS_SELF_DEVELOP
     *
     * @mbg.generated
     */
    private String isSelfDevelop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.IS_MAIN_DRIVE
     *
     * @mbg.generated
     */
    private String isMainDrive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.MAIN_CLASSIFY
     *
     * @mbg.generated
     */
    private String mainClassify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.MAIN_NAME
     *
     * @mbg.generated
     */
    private String mainName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.SHARE_AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal shareAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.SHARE_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal shareProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.LAND_TRANS_AREA
     *
     * @mbg.generated
     */
    private BigDecimal landTransArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.LAND_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal landProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.WAY_WORK_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal wayWorkProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.WAY_OTHERS_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal wayOthersProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.TOTAL_PROCEEDS
     *
     * @mbg.generated
     */
    private BigDecimal totalProceeds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_IDST_PROJWAY.ZONE_YEAR
     *
     * @mbg.generated
     */
    private Long zoneYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_IDST_PROJWAY
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.ID
     *
     * @return the value of TBL_IDST_PROJWAY.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.ID
     *
     * @param id the value for TBL_IDST_PROJWAY.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.DISTRICT_NAME
     *
     * @return the value of TBL_IDST_PROJWAY.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.DISTRICT_NAME
     *
     * @param districtName the value for TBL_IDST_PROJWAY.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.TOWN_NAME
     *
     * @return the value of TBL_IDST_PROJWAY.TOWN_NAME
     *
     * @mbg.generated
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.TOWN_NAME
     *
     * @param townName the value for TBL_IDST_PROJWAY.TOWN_NAME
     *
     * @mbg.generated
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.VILLAGE_NAME
     *
     * @return the value of TBL_IDST_PROJWAY.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.VILLAGE_NAME
     *
     * @param villageName the value for TBL_IDST_PROJWAY.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public void setVillageName(String villageName) {
        this.villageName = villageName == null ? null : villageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.HOLDER_NAME
     *
     * @return the value of TBL_IDST_PROJWAY.HOLDER_NAME
     *
     * @mbg.generated
     */
    public String getHolderName() {
        return holderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.HOLDER_NAME
     *
     * @param holderName the value for TBL_IDST_PROJWAY.HOLDER_NAME
     *
     * @mbg.generated
     */
    public void setHolderName(String holderName) {
        this.holderName = holderName == null ? null : holderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.ID_NUMBER
     *
     * @return the value of TBL_IDST_PROJWAY.ID_NUMBER
     *
     * @mbg.generated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.ID_NUMBER
     *
     * @param idNumber the value for TBL_IDST_PROJWAY.ID_NUMBER
     *
     * @mbg.generated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.FLOWER_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.FLOWER_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getFlowerNum() {
        return flowerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.FLOWER_NUM
     *
     * @param flowerNum the value for TBL_IDST_PROJWAY.FLOWER_NUM
     *
     * @mbg.generated
     */
    public void setFlowerNum(BigDecimal flowerNum) {
        this.flowerNum = flowerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.FLOWER_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.FLOWER_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getFlowerProceeds() {
        return flowerProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.FLOWER_PROCEEDS
     *
     * @param flowerProceeds the value for TBL_IDST_PROJWAY.FLOWER_PROCEEDS
     *
     * @mbg.generated
     */
    public void setFlowerProceeds(BigDecimal flowerProceeds) {
        this.flowerProceeds = flowerProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.IS_JOIN_TOUR
     *
     * @return the value of TBL_IDST_PROJWAY.IS_JOIN_TOUR
     *
     * @mbg.generated
     */
    public String getIsJoinTour() {
        return isJoinTour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.IS_JOIN_TOUR
     *
     * @param isJoinTour the value for TBL_IDST_PROJWAY.IS_JOIN_TOUR
     *
     * @mbg.generated
     */
    public void setIsJoinTour(String isJoinTour) {
        this.isJoinTour = isJoinTour == null ? null : isJoinTour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.TOUR_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.TOUR_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getTourProceeds() {
        return tourProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.TOUR_PROCEEDS
     *
     * @param tourProceeds the value for TBL_IDST_PROJWAY.TOUR_PROCEEDS
     *
     * @mbg.generated
     */
    public void setTourProceeds(BigDecimal tourProceeds) {
        this.tourProceeds = tourProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.EC_SCALE
     *
     * @return the value of TBL_IDST_PROJWAY.EC_SCALE
     *
     * @mbg.generated
     */
    public String getEcScale() {
        return ecScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.EC_SCALE
     *
     * @param ecScale the value for TBL_IDST_PROJWAY.EC_SCALE
     *
     * @mbg.generated
     */
    public void setEcScale(String ecScale) {
        this.ecScale = ecScale == null ? null : ecScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.EC_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.EC_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getEcProceeds() {
        return ecProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.EC_PROCEEDS
     *
     * @param ecProceeds the value for TBL_IDST_PROJWAY.EC_PROCEEDS
     *
     * @mbg.generated
     */
    public void setEcProceeds(BigDecimal ecProceeds) {
        this.ecProceeds = ecProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.VEG_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.VEG_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getVegNum() {
        return vegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.VEG_NUM
     *
     * @param vegNum the value for TBL_IDST_PROJWAY.VEG_NUM
     *
     * @mbg.generated
     */
    public void setVegNum(BigDecimal vegNum) {
        this.vegNum = vegNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.VEG_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.VEG_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getVegProceeds() {
        return vegProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.VEG_PROCEEDS
     *
     * @param vegProceeds the value for TBL_IDST_PROJWAY.VEG_PROCEEDS
     *
     * @mbg.generated
     */
    public void setVegProceeds(BigDecimal vegProceeds) {
        this.vegProceeds = vegProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.YANGTAO_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.YANGTAO_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getYangtaoNum() {
        return yangtaoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.YANGTAO_NUM
     *
     * @param yangtaoNum the value for TBL_IDST_PROJWAY.YANGTAO_NUM
     *
     * @mbg.generated
     */
    public void setYangtaoNum(BigDecimal yangtaoNum) {
        this.yangtaoNum = yangtaoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.YANGTAO_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.YANGTAO_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getYangtaoProceeds() {
        return yangtaoProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.YANGTAO_PROCEEDS
     *
     * @param yangtaoProceeds the value for TBL_IDST_PROJWAY.YANGTAO_PROCEEDS
     *
     * @mbg.generated
     */
    public void setYangtaoProceeds(BigDecimal yangtaoProceeds) {
        this.yangtaoProceeds = yangtaoProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.SHEEP_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.SHEEP_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getSheepNum() {
        return sheepNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.SHEEP_NUM
     *
     * @param sheepNum the value for TBL_IDST_PROJWAY.SHEEP_NUM
     *
     * @mbg.generated
     */
    public void setSheepNum(BigDecimal sheepNum) {
        this.sheepNum = sheepNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.SHEEP_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.SHEEP_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getSheepProceeds() {
        return sheepProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.SHEEP_PROCEEDS
     *
     * @param sheepProceeds the value for TBL_IDST_PROJWAY.SHEEP_PROCEEDS
     *
     * @mbg.generated
     */
    public void setSheepProceeds(BigDecimal sheepProceeds) {
        this.sheepProceeds = sheepProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.BEE_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.BEE_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getBeeNum() {
        return beeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.BEE_NUM
     *
     * @param beeNum the value for TBL_IDST_PROJWAY.BEE_NUM
     *
     * @mbg.generated
     */
    public void setBeeNum(BigDecimal beeNum) {
        this.beeNum = beeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.BEE_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.BEE_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getBeeProceeds() {
        return beeProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.BEE_PROCEEDS
     *
     * @param beeProceeds the value for TBL_IDST_PROJWAY.BEE_PROCEEDS
     *
     * @mbg.generated
     */
    public void setBeeProceeds(BigDecimal beeProceeds) {
        this.beeProceeds = beeProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.WALNUT_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.WALNUT_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getWalnutNum() {
        return walnutNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.WALNUT_NUM
     *
     * @param walnutNum the value for TBL_IDST_PROJWAY.WALNUT_NUM
     *
     * @mbg.generated
     */
    public void setWalnutNum(BigDecimal walnutNum) {
        this.walnutNum = walnutNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.WALNUT_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.WALNUT_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getWalnutProceeds() {
        return walnutProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.WALNUT_PROCEEDS
     *
     * @param walnutProceeds the value for TBL_IDST_PROJWAY.WALNUT_PROCEEDS
     *
     * @mbg.generated
     */
    public void setWalnutProceeds(BigDecimal walnutProceeds) {
        this.walnutProceeds = walnutProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.GRAPE_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.GRAPE_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getGrapeNum() {
        return grapeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.GRAPE_NUM
     *
     * @param grapeNum the value for TBL_IDST_PROJWAY.GRAPE_NUM
     *
     * @mbg.generated
     */
    public void setGrapeNum(BigDecimal grapeNum) {
        this.grapeNum = grapeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.GRAPE_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.GRAPE_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getGrapeProceeds() {
        return grapeProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.GRAPE_PROCEEDS
     *
     * @param grapeProceeds the value for TBL_IDST_PROJWAY.GRAPE_PROCEEDS
     *
     * @mbg.generated
     */
    public void setGrapeProceeds(BigDecimal grapeProceeds) {
        this.grapeProceeds = grapeProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.GRANADA_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.GRANADA_NUM
     *
     * @mbg.generated
     */
    public BigDecimal getGranadaNum() {
        return granadaNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.GRANADA_NUM
     *
     * @param granadaNum the value for TBL_IDST_PROJWAY.GRANADA_NUM
     *
     * @mbg.generated
     */
    public void setGranadaNum(BigDecimal granadaNum) {
        this.granadaNum = granadaNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.GRANADA_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.GRANADA_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getGranadaProceeds() {
        return granadaProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.GRANADA_PROCEEDS
     *
     * @param granadaProceeds the value for TBL_IDST_PROJWAY.GRANADA_PROCEEDS
     *
     * @mbg.generated
     */
    public void setGranadaProceeds(BigDecimal granadaProceeds) {
        this.granadaProceeds = granadaProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.OTHERS_NUM
     *
     * @return the value of TBL_IDST_PROJWAY.OTHERS_NUM
     *
     * @mbg.generated
     */
    public String getOthersNum() {
        return othersNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.OTHERS_NUM
     *
     * @param othersNum the value for TBL_IDST_PROJWAY.OTHERS_NUM
     *
     * @mbg.generated
     */
    public void setOthersNum(String othersNum) {
        this.othersNum = othersNum == null ? null : othersNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.OTHERS_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.OTHERS_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getOthersProceeds() {
        return othersProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.OTHERS_PROCEEDS
     *
     * @param othersProceeds the value for TBL_IDST_PROJWAY.OTHERS_PROCEEDS
     *
     * @mbg.generated
     */
    public void setOthersProceeds(BigDecimal othersProceeds) {
        this.othersProceeds = othersProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.IS_SKILL_TRAIN
     *
     * @return the value of TBL_IDST_PROJWAY.IS_SKILL_TRAIN
     *
     * @mbg.generated
     */
    public String getIsSkillTrain() {
        return isSkillTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.IS_SKILL_TRAIN
     *
     * @param isSkillTrain the value for TBL_IDST_PROJWAY.IS_SKILL_TRAIN
     *
     * @mbg.generated
     */
    public void setIsSkillTrain(String isSkillTrain) {
        this.isSkillTrain = isSkillTrain == null ? null : isSkillTrain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.IS_SELF_DEVELOP
     *
     * @return the value of TBL_IDST_PROJWAY.IS_SELF_DEVELOP
     *
     * @mbg.generated
     */
    public String getIsSelfDevelop() {
        return isSelfDevelop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.IS_SELF_DEVELOP
     *
     * @param isSelfDevelop the value for TBL_IDST_PROJWAY.IS_SELF_DEVELOP
     *
     * @mbg.generated
     */
    public void setIsSelfDevelop(String isSelfDevelop) {
        this.isSelfDevelop = isSelfDevelop == null ? null : isSelfDevelop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.IS_MAIN_DRIVE
     *
     * @return the value of TBL_IDST_PROJWAY.IS_MAIN_DRIVE
     *
     * @mbg.generated
     */
    public String getIsMainDrive() {
        return isMainDrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.IS_MAIN_DRIVE
     *
     * @param isMainDrive the value for TBL_IDST_PROJWAY.IS_MAIN_DRIVE
     *
     * @mbg.generated
     */
    public void setIsMainDrive(String isMainDrive) {
        this.isMainDrive = isMainDrive == null ? null : isMainDrive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.MAIN_CLASSIFY
     *
     * @return the value of TBL_IDST_PROJWAY.MAIN_CLASSIFY
     *
     * @mbg.generated
     */
    public String getMainClassify() {
        return mainClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.MAIN_CLASSIFY
     *
     * @param mainClassify the value for TBL_IDST_PROJWAY.MAIN_CLASSIFY
     *
     * @mbg.generated
     */
    public void setMainClassify(String mainClassify) {
        this.mainClassify = mainClassify == null ? null : mainClassify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.MAIN_NAME
     *
     * @return the value of TBL_IDST_PROJWAY.MAIN_NAME
     *
     * @mbg.generated
     */
    public String getMainName() {
        return mainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.MAIN_NAME
     *
     * @param mainName the value for TBL_IDST_PROJWAY.MAIN_NAME
     *
     * @mbg.generated
     */
    public void setMainName(String mainName) {
        this.mainName = mainName == null ? null : mainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.SHARE_AMOUNT
     *
     * @return the value of TBL_IDST_PROJWAY.SHARE_AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getShareAmount() {
        return shareAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.SHARE_AMOUNT
     *
     * @param shareAmount the value for TBL_IDST_PROJWAY.SHARE_AMOUNT
     *
     * @mbg.generated
     */
    public void setShareAmount(BigDecimal shareAmount) {
        this.shareAmount = shareAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.SHARE_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.SHARE_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getShareProceeds() {
        return shareProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.SHARE_PROCEEDS
     *
     * @param shareProceeds the value for TBL_IDST_PROJWAY.SHARE_PROCEEDS
     *
     * @mbg.generated
     */
    public void setShareProceeds(BigDecimal shareProceeds) {
        this.shareProceeds = shareProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.LAND_TRANS_AREA
     *
     * @return the value of TBL_IDST_PROJWAY.LAND_TRANS_AREA
     *
     * @mbg.generated
     */
    public BigDecimal getLandTransArea() {
        return landTransArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.LAND_TRANS_AREA
     *
     * @param landTransArea the value for TBL_IDST_PROJWAY.LAND_TRANS_AREA
     *
     * @mbg.generated
     */
    public void setLandTransArea(BigDecimal landTransArea) {
        this.landTransArea = landTransArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.LAND_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.LAND_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getLandProceeds() {
        return landProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.LAND_PROCEEDS
     *
     * @param landProceeds the value for TBL_IDST_PROJWAY.LAND_PROCEEDS
     *
     * @mbg.generated
     */
    public void setLandProceeds(BigDecimal landProceeds) {
        this.landProceeds = landProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.WAY_WORK_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.WAY_WORK_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getWayWorkProceeds() {
        return wayWorkProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.WAY_WORK_PROCEEDS
     *
     * @param wayWorkProceeds the value for TBL_IDST_PROJWAY.WAY_WORK_PROCEEDS
     *
     * @mbg.generated
     */
    public void setWayWorkProceeds(BigDecimal wayWorkProceeds) {
        this.wayWorkProceeds = wayWorkProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.WAY_OTHERS_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.WAY_OTHERS_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getWayOthersProceeds() {
        return wayOthersProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.WAY_OTHERS_PROCEEDS
     *
     * @param wayOthersProceeds the value for TBL_IDST_PROJWAY.WAY_OTHERS_PROCEEDS
     *
     * @mbg.generated
     */
    public void setWayOthersProceeds(BigDecimal wayOthersProceeds) {
        this.wayOthersProceeds = wayOthersProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.TOTAL_PROCEEDS
     *
     * @return the value of TBL_IDST_PROJWAY.TOTAL_PROCEEDS
     *
     * @mbg.generated
     */
    public BigDecimal getTotalProceeds() {
        return totalProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.TOTAL_PROCEEDS
     *
     * @param totalProceeds the value for TBL_IDST_PROJWAY.TOTAL_PROCEEDS
     *
     * @mbg.generated
     */
    public void setTotalProceeds(BigDecimal totalProceeds) {
        this.totalProceeds = totalProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.REMARKS
     *
     * @return the value of TBL_IDST_PROJWAY.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.REMARKS
     *
     * @param remarks the value for TBL_IDST_PROJWAY.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_IDST_PROJWAY.ZONE_YEAR
     *
     * @return the value of TBL_IDST_PROJWAY.ZONE_YEAR
     *
     * @mbg.generated
     */
    public Long getZoneYear() {
        return zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_IDST_PROJWAY.ZONE_YEAR
     *
     * @param zoneYear the value for TBL_IDST_PROJWAY.ZONE_YEAR
     *
     * @mbg.generated
     */
    public void setZoneYear(Long zoneYear) {
        this.zoneYear = zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IDST_PROJWAY
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IdstProjwayDD other = (IdstProjwayDD) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getTownName() == null ? other.getTownName() == null : this.getTownName().equals(other.getTownName()))
            && (this.getVillageName() == null ? other.getVillageName() == null : this.getVillageName().equals(other.getVillageName()))
            && (this.getHolderName() == null ? other.getHolderName() == null : this.getHolderName().equals(other.getHolderName()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getFlowerNum() == null ? other.getFlowerNum() == null : this.getFlowerNum().equals(other.getFlowerNum()))
            && (this.getFlowerProceeds() == null ? other.getFlowerProceeds() == null : this.getFlowerProceeds().equals(other.getFlowerProceeds()))
            && (this.getIsJoinTour() == null ? other.getIsJoinTour() == null : this.getIsJoinTour().equals(other.getIsJoinTour()))
            && (this.getTourProceeds() == null ? other.getTourProceeds() == null : this.getTourProceeds().equals(other.getTourProceeds()))
            && (this.getEcScale() == null ? other.getEcScale() == null : this.getEcScale().equals(other.getEcScale()))
            && (this.getEcProceeds() == null ? other.getEcProceeds() == null : this.getEcProceeds().equals(other.getEcProceeds()))
            && (this.getVegNum() == null ? other.getVegNum() == null : this.getVegNum().equals(other.getVegNum()))
            && (this.getVegProceeds() == null ? other.getVegProceeds() == null : this.getVegProceeds().equals(other.getVegProceeds()))
            && (this.getYangtaoNum() == null ? other.getYangtaoNum() == null : this.getYangtaoNum().equals(other.getYangtaoNum()))
            && (this.getYangtaoProceeds() == null ? other.getYangtaoProceeds() == null : this.getYangtaoProceeds().equals(other.getYangtaoProceeds()))
            && (this.getSheepNum() == null ? other.getSheepNum() == null : this.getSheepNum().equals(other.getSheepNum()))
            && (this.getSheepProceeds() == null ? other.getSheepProceeds() == null : this.getSheepProceeds().equals(other.getSheepProceeds()))
            && (this.getBeeNum() == null ? other.getBeeNum() == null : this.getBeeNum().equals(other.getBeeNum()))
            && (this.getBeeProceeds() == null ? other.getBeeProceeds() == null : this.getBeeProceeds().equals(other.getBeeProceeds()))
            && (this.getWalnutNum() == null ? other.getWalnutNum() == null : this.getWalnutNum().equals(other.getWalnutNum()))
            && (this.getWalnutProceeds() == null ? other.getWalnutProceeds() == null : this.getWalnutProceeds().equals(other.getWalnutProceeds()))
            && (this.getGrapeNum() == null ? other.getGrapeNum() == null : this.getGrapeNum().equals(other.getGrapeNum()))
            && (this.getGrapeProceeds() == null ? other.getGrapeProceeds() == null : this.getGrapeProceeds().equals(other.getGrapeProceeds()))
            && (this.getGranadaNum() == null ? other.getGranadaNum() == null : this.getGranadaNum().equals(other.getGranadaNum()))
            && (this.getGranadaProceeds() == null ? other.getGranadaProceeds() == null : this.getGranadaProceeds().equals(other.getGranadaProceeds()))
            && (this.getOthersNum() == null ? other.getOthersNum() == null : this.getOthersNum().equals(other.getOthersNum()))
            && (this.getOthersProceeds() == null ? other.getOthersProceeds() == null : this.getOthersProceeds().equals(other.getOthersProceeds()))
            && (this.getIsSkillTrain() == null ? other.getIsSkillTrain() == null : this.getIsSkillTrain().equals(other.getIsSkillTrain()))
            && (this.getIsSelfDevelop() == null ? other.getIsSelfDevelop() == null : this.getIsSelfDevelop().equals(other.getIsSelfDevelop()))
            && (this.getIsMainDrive() == null ? other.getIsMainDrive() == null : this.getIsMainDrive().equals(other.getIsMainDrive()))
            && (this.getMainClassify() == null ? other.getMainClassify() == null : this.getMainClassify().equals(other.getMainClassify()))
            && (this.getMainName() == null ? other.getMainName() == null : this.getMainName().equals(other.getMainName()))
            && (this.getShareAmount() == null ? other.getShareAmount() == null : this.getShareAmount().equals(other.getShareAmount()))
            && (this.getShareProceeds() == null ? other.getShareProceeds() == null : this.getShareProceeds().equals(other.getShareProceeds()))
            && (this.getLandTransArea() == null ? other.getLandTransArea() == null : this.getLandTransArea().equals(other.getLandTransArea()))
            && (this.getLandProceeds() == null ? other.getLandProceeds() == null : this.getLandProceeds().equals(other.getLandProceeds()))
            && (this.getWayWorkProceeds() == null ? other.getWayWorkProceeds() == null : this.getWayWorkProceeds().equals(other.getWayWorkProceeds()))
            && (this.getWayOthersProceeds() == null ? other.getWayOthersProceeds() == null : this.getWayOthersProceeds().equals(other.getWayOthersProceeds()))
            && (this.getTotalProceeds() == null ? other.getTotalProceeds() == null : this.getTotalProceeds().equals(other.getTotalProceeds()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getZoneYear() == null ? other.getZoneYear() == null : this.getZoneYear().equals(other.getZoneYear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IDST_PROJWAY
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getTownName() == null) ? 0 : getTownName().hashCode());
        result = prime * result + ((getVillageName() == null) ? 0 : getVillageName().hashCode());
        result = prime * result + ((getHolderName() == null) ? 0 : getHolderName().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getFlowerNum() == null) ? 0 : getFlowerNum().hashCode());
        result = prime * result + ((getFlowerProceeds() == null) ? 0 : getFlowerProceeds().hashCode());
        result = prime * result + ((getIsJoinTour() == null) ? 0 : getIsJoinTour().hashCode());
        result = prime * result + ((getTourProceeds() == null) ? 0 : getTourProceeds().hashCode());
        result = prime * result + ((getEcScale() == null) ? 0 : getEcScale().hashCode());
        result = prime * result + ((getEcProceeds() == null) ? 0 : getEcProceeds().hashCode());
        result = prime * result + ((getVegNum() == null) ? 0 : getVegNum().hashCode());
        result = prime * result + ((getVegProceeds() == null) ? 0 : getVegProceeds().hashCode());
        result = prime * result + ((getYangtaoNum() == null) ? 0 : getYangtaoNum().hashCode());
        result = prime * result + ((getYangtaoProceeds() == null) ? 0 : getYangtaoProceeds().hashCode());
        result = prime * result + ((getSheepNum() == null) ? 0 : getSheepNum().hashCode());
        result = prime * result + ((getSheepProceeds() == null) ? 0 : getSheepProceeds().hashCode());
        result = prime * result + ((getBeeNum() == null) ? 0 : getBeeNum().hashCode());
        result = prime * result + ((getBeeProceeds() == null) ? 0 : getBeeProceeds().hashCode());
        result = prime * result + ((getWalnutNum() == null) ? 0 : getWalnutNum().hashCode());
        result = prime * result + ((getWalnutProceeds() == null) ? 0 : getWalnutProceeds().hashCode());
        result = prime * result + ((getGrapeNum() == null) ? 0 : getGrapeNum().hashCode());
        result = prime * result + ((getGrapeProceeds() == null) ? 0 : getGrapeProceeds().hashCode());
        result = prime * result + ((getGranadaNum() == null) ? 0 : getGranadaNum().hashCode());
        result = prime * result + ((getGranadaProceeds() == null) ? 0 : getGranadaProceeds().hashCode());
        result = prime * result + ((getOthersNum() == null) ? 0 : getOthersNum().hashCode());
        result = prime * result + ((getOthersProceeds() == null) ? 0 : getOthersProceeds().hashCode());
        result = prime * result + ((getIsSkillTrain() == null) ? 0 : getIsSkillTrain().hashCode());
        result = prime * result + ((getIsSelfDevelop() == null) ? 0 : getIsSelfDevelop().hashCode());
        result = prime * result + ((getIsMainDrive() == null) ? 0 : getIsMainDrive().hashCode());
        result = prime * result + ((getMainClassify() == null) ? 0 : getMainClassify().hashCode());
        result = prime * result + ((getMainName() == null) ? 0 : getMainName().hashCode());
        result = prime * result + ((getShareAmount() == null) ? 0 : getShareAmount().hashCode());
        result = prime * result + ((getShareProceeds() == null) ? 0 : getShareProceeds().hashCode());
        result = prime * result + ((getLandTransArea() == null) ? 0 : getLandTransArea().hashCode());
        result = prime * result + ((getLandProceeds() == null) ? 0 : getLandProceeds().hashCode());
        result = prime * result + ((getWayWorkProceeds() == null) ? 0 : getWayWorkProceeds().hashCode());
        result = prime * result + ((getWayOthersProceeds() == null) ? 0 : getWayOthersProceeds().hashCode());
        result = prime * result + ((getTotalProceeds() == null) ? 0 : getTotalProceeds().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getZoneYear() == null) ? 0 : getZoneYear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_IDST_PROJWAY
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", districtName=").append(districtName);
        sb.append(", townName=").append(townName);
        sb.append(", villageName=").append(villageName);
        sb.append(", holderName=").append(holderName);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", flowerNum=").append(flowerNum);
        sb.append(", flowerProceeds=").append(flowerProceeds);
        sb.append(", isJoinTour=").append(isJoinTour);
        sb.append(", tourProceeds=").append(tourProceeds);
        sb.append(", ecScale=").append(ecScale);
        sb.append(", ecProceeds=").append(ecProceeds);
        sb.append(", vegNum=").append(vegNum);
        sb.append(", vegProceeds=").append(vegProceeds);
        sb.append(", yangtaoNum=").append(yangtaoNum);
        sb.append(", yangtaoProceeds=").append(yangtaoProceeds);
        sb.append(", sheepNum=").append(sheepNum);
        sb.append(", sheepProceeds=").append(sheepProceeds);
        sb.append(", beeNum=").append(beeNum);
        sb.append(", beeProceeds=").append(beeProceeds);
        sb.append(", walnutNum=").append(walnutNum);
        sb.append(", walnutProceeds=").append(walnutProceeds);
        sb.append(", grapeNum=").append(grapeNum);
        sb.append(", grapeProceeds=").append(grapeProceeds);
        sb.append(", granadaNum=").append(granadaNum);
        sb.append(", granadaProceeds=").append(granadaProceeds);
        sb.append(", othersNum=").append(othersNum);
        sb.append(", othersProceeds=").append(othersProceeds);
        sb.append(", isSkillTrain=").append(isSkillTrain);
        sb.append(", isSelfDevelop=").append(isSelfDevelop);
        sb.append(", isMainDrive=").append(isMainDrive);
        sb.append(", mainClassify=").append(mainClassify);
        sb.append(", mainName=").append(mainName);
        sb.append(", shareAmount=").append(shareAmount);
        sb.append(", shareProceeds=").append(shareProceeds);
        sb.append(", landTransArea=").append(landTransArea);
        sb.append(", landProceeds=").append(landProceeds);
        sb.append(", wayWorkProceeds=").append(wayWorkProceeds);
        sb.append(", wayOthersProceeds=").append(wayOthersProceeds);
        sb.append(", totalProceeds=").append(totalProceeds);
        sb.append(", remarks=").append(remarks);
        sb.append(", zoneYear=").append(zoneYear);
        sb.append("]");
        return sb.toString();
    }
}