package com.sysh.entity.helpmea;

import java.io.Serializable;
import java.math.BigDecimal;

public class ReconstDangerDD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.DISTRICT_NAME
     *
     * @mbg.generated
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.TOWN_NAME
     *
     * @mbg.generated
     */
    private String townName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.VILLAGE_NAME
     *
     * @mbg.generated
     */
    private String villageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.POVERTY_NAME
     *
     * @mbg.generated
     */
    private String povertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.ID_NUMBER
     *
     * @mbg.generated
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.IS_START
     *
     * @mbg.generated
     */
    private String isStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.START_TIME
     *
     * @mbg.generated
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.IS_COMPLETE
     *
     * @mbg.generated
     */
    private String isComplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.COMPLETE_TIME
     *
     * @mbg.generated
     */
    private String completeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.IS_ACCEPTANCE
     *
     * @mbg.generated
     */
    private String isAcceptance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.ACCEPT_TIME
     *
     * @mbg.generated
     */
    private String acceptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.IS_CHECKIN
     *
     * @mbg.generated
     */
    private String isCheckin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.CHECKIN_TIME
     *
     * @mbg.generated
     */
    private String checkinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.HOUSE_AREA
     *
     * @mbg.generated
     */
    private String houseArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.HOUSING_SUBSIDY
     *
     * @mbg.generated
     */
    private BigDecimal housingSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.PERSON_RAISE
     *
     * @mbg.generated
     */
    private BigDecimal personRaise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.START_BEFORE
     *
     * @mbg.generated
     */
    private String startBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.CONSTRUCTION
     *
     * @mbg.generated
     */
    private String construction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.AFTER_COMPLETETION
     *
     * @mbg.generated
     */
    private String afterCompletetion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.AFTER_CHECKIN
     *
     * @mbg.generated
     */
    private String afterCheckin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.REMARKS
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_RECONST_DANGER.ZONE_YEAR
     *
     * @mbg.generated
     */
    private Long zoneYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.ID
     *
     * @return the value of TBL_RECONST_DANGER.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.ID
     *
     * @param id the value for TBL_RECONST_DANGER.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.DISTRICT_NAME
     *
     * @return the value of TBL_RECONST_DANGER.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.DISTRICT_NAME
     *
     * @param districtName the value for TBL_RECONST_DANGER.DISTRICT_NAME
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.TOWN_NAME
     *
     * @return the value of TBL_RECONST_DANGER.TOWN_NAME
     *
     * @mbg.generated
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.TOWN_NAME
     *
     * @param townName the value for TBL_RECONST_DANGER.TOWN_NAME
     *
     * @mbg.generated
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.VILLAGE_NAME
     *
     * @return the value of TBL_RECONST_DANGER.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.VILLAGE_NAME
     *
     * @param villageName the value for TBL_RECONST_DANGER.VILLAGE_NAME
     *
     * @mbg.generated
     */
    public void setVillageName(String villageName) {
        this.villageName = villageName == null ? null : villageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.POVERTY_NAME
     *
     * @return the value of TBL_RECONST_DANGER.POVERTY_NAME
     *
     * @mbg.generated
     */
    public String getPovertyName() {
        return povertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.POVERTY_NAME
     *
     * @param povertyName the value for TBL_RECONST_DANGER.POVERTY_NAME
     *
     * @mbg.generated
     */
    public void setPovertyName(String povertyName) {
        this.povertyName = povertyName == null ? null : povertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.ID_NUMBER
     *
     * @return the value of TBL_RECONST_DANGER.ID_NUMBER
     *
     * @mbg.generated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.ID_NUMBER
     *
     * @param idNumber the value for TBL_RECONST_DANGER.ID_NUMBER
     *
     * @mbg.generated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.IS_START
     *
     * @return the value of TBL_RECONST_DANGER.IS_START
     *
     * @mbg.generated
     */
    public String getIsStart() {
        return isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.IS_START
     *
     * @param isStart the value for TBL_RECONST_DANGER.IS_START
     *
     * @mbg.generated
     */
    public void setIsStart(String isStart) {
        this.isStart = isStart == null ? null : isStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.START_TIME
     *
     * @return the value of TBL_RECONST_DANGER.START_TIME
     *
     * @mbg.generated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.START_TIME
     *
     * @param startTime the value for TBL_RECONST_DANGER.START_TIME
     *
     * @mbg.generated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.IS_COMPLETE
     *
     * @return the value of TBL_RECONST_DANGER.IS_COMPLETE
     *
     * @mbg.generated
     */
    public String getIsComplete() {
        return isComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.IS_COMPLETE
     *
     * @param isComplete the value for TBL_RECONST_DANGER.IS_COMPLETE
     *
     * @mbg.generated
     */
    public void setIsComplete(String isComplete) {
        this.isComplete = isComplete == null ? null : isComplete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.COMPLETE_TIME
     *
     * @return the value of TBL_RECONST_DANGER.COMPLETE_TIME
     *
     * @mbg.generated
     */
    public String getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.COMPLETE_TIME
     *
     * @param completeTime the value for TBL_RECONST_DANGER.COMPLETE_TIME
     *
     * @mbg.generated
     */
    public void setCompleteTime(String completeTime) {
        this.completeTime = completeTime == null ? null : completeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.IS_ACCEPTANCE
     *
     * @return the value of TBL_RECONST_DANGER.IS_ACCEPTANCE
     *
     * @mbg.generated
     */
    public String getIsAcceptance() {
        return isAcceptance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.IS_ACCEPTANCE
     *
     * @param isAcceptance the value for TBL_RECONST_DANGER.IS_ACCEPTANCE
     *
     * @mbg.generated
     */
    public void setIsAcceptance(String isAcceptance) {
        this.isAcceptance = isAcceptance == null ? null : isAcceptance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.ACCEPT_TIME
     *
     * @return the value of TBL_RECONST_DANGER.ACCEPT_TIME
     *
     * @mbg.generated
     */
    public String getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.ACCEPT_TIME
     *
     * @param acceptTime the value for TBL_RECONST_DANGER.ACCEPT_TIME
     *
     * @mbg.generated
     */
    public void setAcceptTime(String acceptTime) {
        this.acceptTime = acceptTime == null ? null : acceptTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.IS_CHECKIN
     *
     * @return the value of TBL_RECONST_DANGER.IS_CHECKIN
     *
     * @mbg.generated
     */
    public String getIsCheckin() {
        return isCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.IS_CHECKIN
     *
     * @param isCheckin the value for TBL_RECONST_DANGER.IS_CHECKIN
     *
     * @mbg.generated
     */
    public void setIsCheckin(String isCheckin) {
        this.isCheckin = isCheckin == null ? null : isCheckin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.CHECKIN_TIME
     *
     * @return the value of TBL_RECONST_DANGER.CHECKIN_TIME
     *
     * @mbg.generated
     */
    public String getCheckinTime() {
        return checkinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.CHECKIN_TIME
     *
     * @param checkinTime the value for TBL_RECONST_DANGER.CHECKIN_TIME
     *
     * @mbg.generated
     */
    public void setCheckinTime(String checkinTime) {
        this.checkinTime = checkinTime == null ? null : checkinTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.HOUSE_AREA
     *
     * @return the value of TBL_RECONST_DANGER.HOUSE_AREA
     *
     * @mbg.generated
     */
    public String getHouseArea() {
        return houseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.HOUSE_AREA
     *
     * @param houseArea the value for TBL_RECONST_DANGER.HOUSE_AREA
     *
     * @mbg.generated
     */
    public void setHouseArea(String houseArea) {
        this.houseArea = houseArea == null ? null : houseArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.HOUSING_SUBSIDY
     *
     * @return the value of TBL_RECONST_DANGER.HOUSING_SUBSIDY
     *
     * @mbg.generated
     */
    public BigDecimal getHousingSubsidy() {
        return housingSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.HOUSING_SUBSIDY
     *
     * @param housingSubsidy the value for TBL_RECONST_DANGER.HOUSING_SUBSIDY
     *
     * @mbg.generated
     */
    public void setHousingSubsidy(BigDecimal housingSubsidy) {
        this.housingSubsidy = housingSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.PERSON_RAISE
     *
     * @return the value of TBL_RECONST_DANGER.PERSON_RAISE
     *
     * @mbg.generated
     */
    public BigDecimal getPersonRaise() {
        return personRaise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.PERSON_RAISE
     *
     * @param personRaise the value for TBL_RECONST_DANGER.PERSON_RAISE
     *
     * @mbg.generated
     */
    public void setPersonRaise(BigDecimal personRaise) {
        this.personRaise = personRaise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.START_BEFORE
     *
     * @return the value of TBL_RECONST_DANGER.START_BEFORE
     *
     * @mbg.generated
     */
    public String getStartBefore() {
        return startBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.START_BEFORE
     *
     * @param startBefore the value for TBL_RECONST_DANGER.START_BEFORE
     *
     * @mbg.generated
     */
    public void setStartBefore(String startBefore) {
        this.startBefore = startBefore == null ? null : startBefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.CONSTRUCTION
     *
     * @return the value of TBL_RECONST_DANGER.CONSTRUCTION
     *
     * @mbg.generated
     */
    public String getConstruction() {
        return construction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.CONSTRUCTION
     *
     * @param construction the value for TBL_RECONST_DANGER.CONSTRUCTION
     *
     * @mbg.generated
     */
    public void setConstruction(String construction) {
        this.construction = construction == null ? null : construction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.AFTER_COMPLETETION
     *
     * @return the value of TBL_RECONST_DANGER.AFTER_COMPLETETION
     *
     * @mbg.generated
     */
    public String getAfterCompletetion() {
        return afterCompletetion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.AFTER_COMPLETETION
     *
     * @param afterCompletetion the value for TBL_RECONST_DANGER.AFTER_COMPLETETION
     *
     * @mbg.generated
     */
    public void setAfterCompletetion(String afterCompletetion) {
        this.afterCompletetion = afterCompletetion == null ? null : afterCompletetion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.AFTER_CHECKIN
     *
     * @return the value of TBL_RECONST_DANGER.AFTER_CHECKIN
     *
     * @mbg.generated
     */
    public String getAfterCheckin() {
        return afterCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.AFTER_CHECKIN
     *
     * @param afterCheckin the value for TBL_RECONST_DANGER.AFTER_CHECKIN
     *
     * @mbg.generated
     */
    public void setAfterCheckin(String afterCheckin) {
        this.afterCheckin = afterCheckin == null ? null : afterCheckin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.REMARKS
     *
     * @return the value of TBL_RECONST_DANGER.REMARKS
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.REMARKS
     *
     * @param remarks the value for TBL_RECONST_DANGER.REMARKS
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_RECONST_DANGER.ZONE_YEAR
     *
     * @return the value of TBL_RECONST_DANGER.ZONE_YEAR
     *
     * @mbg.generated
     */
    public Long getZoneYear() {
        return zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_RECONST_DANGER.ZONE_YEAR
     *
     * @param zoneYear the value for TBL_RECONST_DANGER.ZONE_YEAR
     *
     * @mbg.generated
     */
    public void setZoneYear(Long zoneYear) {
        this.zoneYear = zoneYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ReconstDangerDD other = (ReconstDangerDD) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDistrictName() == null ? other.getDistrictName() == null : this.getDistrictName().equals(other.getDistrictName()))
            && (this.getTownName() == null ? other.getTownName() == null : this.getTownName().equals(other.getTownName()))
            && (this.getVillageName() == null ? other.getVillageName() == null : this.getVillageName().equals(other.getVillageName()))
            && (this.getPovertyName() == null ? other.getPovertyName() == null : this.getPovertyName().equals(other.getPovertyName()))
            && (this.getIdNumber() == null ? other.getIdNumber() == null : this.getIdNumber().equals(other.getIdNumber()))
            && (this.getIsStart() == null ? other.getIsStart() == null : this.getIsStart().equals(other.getIsStart()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getIsComplete() == null ? other.getIsComplete() == null : this.getIsComplete().equals(other.getIsComplete()))
            && (this.getCompleteTime() == null ? other.getCompleteTime() == null : this.getCompleteTime().equals(other.getCompleteTime()))
            && (this.getIsAcceptance() == null ? other.getIsAcceptance() == null : this.getIsAcceptance().equals(other.getIsAcceptance()))
            && (this.getAcceptTime() == null ? other.getAcceptTime() == null : this.getAcceptTime().equals(other.getAcceptTime()))
            && (this.getIsCheckin() == null ? other.getIsCheckin() == null : this.getIsCheckin().equals(other.getIsCheckin()))
            && (this.getCheckinTime() == null ? other.getCheckinTime() == null : this.getCheckinTime().equals(other.getCheckinTime()))
            && (this.getHouseArea() == null ? other.getHouseArea() == null : this.getHouseArea().equals(other.getHouseArea()))
            && (this.getHousingSubsidy() == null ? other.getHousingSubsidy() == null : this.getHousingSubsidy().equals(other.getHousingSubsidy()))
            && (this.getPersonRaise() == null ? other.getPersonRaise() == null : this.getPersonRaise().equals(other.getPersonRaise()))
            && (this.getStartBefore() == null ? other.getStartBefore() == null : this.getStartBefore().equals(other.getStartBefore()))
            && (this.getConstruction() == null ? other.getConstruction() == null : this.getConstruction().equals(other.getConstruction()))
            && (this.getAfterCompletetion() == null ? other.getAfterCompletetion() == null : this.getAfterCompletetion().equals(other.getAfterCompletetion()))
            && (this.getAfterCheckin() == null ? other.getAfterCheckin() == null : this.getAfterCheckin().equals(other.getAfterCheckin()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getZoneYear() == null ? other.getZoneYear() == null : this.getZoneYear().equals(other.getZoneYear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDistrictName() == null) ? 0 : getDistrictName().hashCode());
        result = prime * result + ((getTownName() == null) ? 0 : getTownName().hashCode());
        result = prime * result + ((getVillageName() == null) ? 0 : getVillageName().hashCode());
        result = prime * result + ((getPovertyName() == null) ? 0 : getPovertyName().hashCode());
        result = prime * result + ((getIdNumber() == null) ? 0 : getIdNumber().hashCode());
        result = prime * result + ((getIsStart() == null) ? 0 : getIsStart().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getIsComplete() == null) ? 0 : getIsComplete().hashCode());
        result = prime * result + ((getCompleteTime() == null) ? 0 : getCompleteTime().hashCode());
        result = prime * result + ((getIsAcceptance() == null) ? 0 : getIsAcceptance().hashCode());
        result = prime * result + ((getAcceptTime() == null) ? 0 : getAcceptTime().hashCode());
        result = prime * result + ((getIsCheckin() == null) ? 0 : getIsCheckin().hashCode());
        result = prime * result + ((getCheckinTime() == null) ? 0 : getCheckinTime().hashCode());
        result = prime * result + ((getHouseArea() == null) ? 0 : getHouseArea().hashCode());
        result = prime * result + ((getHousingSubsidy() == null) ? 0 : getHousingSubsidy().hashCode());
        result = prime * result + ((getPersonRaise() == null) ? 0 : getPersonRaise().hashCode());
        result = prime * result + ((getStartBefore() == null) ? 0 : getStartBefore().hashCode());
        result = prime * result + ((getConstruction() == null) ? 0 : getConstruction().hashCode());
        result = prime * result + ((getAfterCompletetion() == null) ? 0 : getAfterCompletetion().hashCode());
        result = prime * result + ((getAfterCheckin() == null) ? 0 : getAfterCheckin().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getZoneYear() == null) ? 0 : getZoneYear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_RECONST_DANGER
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", districtName=").append(districtName);
        sb.append(", townName=").append(townName);
        sb.append(", villageName=").append(villageName);
        sb.append(", povertyName=").append(povertyName);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", isStart=").append(isStart);
        sb.append(", startTime=").append(startTime);
        sb.append(", isComplete=").append(isComplete);
        sb.append(", completeTime=").append(completeTime);
        sb.append(", isAcceptance=").append(isAcceptance);
        sb.append(", acceptTime=").append(acceptTime);
        sb.append(", isCheckin=").append(isCheckin);
        sb.append(", checkinTime=").append(checkinTime);
        sb.append(", houseArea=").append(houseArea);
        sb.append(", housingSubsidy=").append(housingSubsidy);
        sb.append(", personRaise=").append(personRaise);
        sb.append(", startBefore=").append(startBefore);
        sb.append(", construction=").append(construction);
        sb.append(", afterCompletetion=").append(afterCompletetion);
        sb.append(", afterCheckin=").append(afterCheckin);
        sb.append(", remarks=").append(remarks);
        sb.append(", zoneYear=").append(zoneYear);
        sb.append("]");
        return sb.toString();
    }
}