package com.sysh.entity;

import java.io.Serializable;
import java.util.Date;

public class AK11DD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAK110
     *
     * @mbg.generated
     */
    private Long aak110;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAP110
     *
     * @mbg.generated
     */
    private Long aap110;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAB002
     *
     * @mbg.generated
     */
    private String aab002;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAK032
     *
     * @mbg.generated
     */
    private String aak032;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAK031
     *
     * @mbg.generated
     */
    private String aak031;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAK039
     *
     * @mbg.generated
     */
    private String aak039;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAB003
     *
     * @mbg.generated
     */
    private String aab003;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAB004
     *
     * @mbg.generated
     */
    private String aab004;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR011
     *
     * @mbg.generated
     */
    private String aar011;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR012
     *
     * @mbg.generated
     */
    private String aar012;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR013
     *
     * @mbg.generated
     */
    private String aar013;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAP001
     *
     * @mbg.generated
     */
    private String aap001;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAP004
     *
     * @mbg.generated
     */
    private String aap004;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAK033
     *
     * @mbg.generated
     */
    private String aak033;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAB005
     *
     * @mbg.generated
     */
    private Long aab005;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAF031
     *
     * @mbg.generated
     */
    private String aaf031;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAK036
     *
     * @mbg.generated
     */
    private String aak036;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAK037
     *
     * @mbg.generated
     */
    private String aak037;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR001
     *
     * @mbg.generated
     */
    private String aar001;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR022
     *
     * @mbg.generated
     */
    private String aar022;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR023
     *
     * @mbg.generated
     */
    private String aar023;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR024
     *
     * @mbg.generated
     */
    private Long aar024;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR025
     *
     * @mbg.generated
     */
    private String aar025;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.BAZ002
     *
     * @mbg.generated
     */
    private Long baz002;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAR008
     *
     * @mbg.generated
     */
    private String aar008;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.AAK111
     *
     * @mbg.generated
     */
    private String aak111;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AK11.TIMESTAMP
     *
     * @mbg.generated
     */
    private Date timestamp;

    private String aak666;
    private String aak777;
    private String aak888;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AK11
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAK110
     *
     * @return the value of AK11.AAK110
     *
     * @mbg.generated
     */
    public Long getAak110() {
        return aak110;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAK110
     *
     * @param aak110 the value for AK11.AAK110
     *
     * @mbg.generated
     */
    public void setAak110(Long aak110) {
        this.aak110 = aak110;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAP110
     *
     * @return the value of AK11.AAP110
     *
     * @mbg.generated
     */
    public Long getAap110() {
        return aap110;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAP110
     *
     * @param aap110 the value for AK11.AAP110
     *
     * @mbg.generated
     */
    public void setAap110(Long aap110) {
        this.aap110 = aap110;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAB002
     *
     * @return the value of AK11.AAB002
     *
     * @mbg.generated
     */
    public String getAab002() {
        return aab002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAB002
     *
     * @param aab002 the value for AK11.AAB002
     *
     * @mbg.generated
     */
    public void setAab002(String aab002) {
        this.aab002 = aab002 == null ? null : aab002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAK032
     *
     * @return the value of AK11.AAK032
     *
     * @mbg.generated
     */
    public String getAak032() {
        return aak032;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAK032
     *
     * @param aak032 the value for AK11.AAK032
     *
     * @mbg.generated
     */
    public void setAak032(String aak032) {
        this.aak032 = aak032 == null ? null : aak032.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAK031
     *
     * @return the value of AK11.AAK031
     *
     * @mbg.generated
     */
    public String getAak031() {
        return aak031;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAK031
     *
     * @param aak031 the value for AK11.AAK031
     *
     * @mbg.generated
     */
    public void setAak031(String aak031) {
        this.aak031 = aak031 == null ? null : aak031.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAK039
     *
     * @return the value of AK11.AAK039
     *
     * @mbg.generated
     */
    public String getAak039() {
        return aak039;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAK039
     *
     * @param aak039 the value for AK11.AAK039
     *
     * @mbg.generated
     */
    public void setAak039(String aak039) {
        this.aak039 = aak039 == null ? null : aak039.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAB003
     *
     * @return the value of AK11.AAB003
     *
     * @mbg.generated
     */
    public String getAab003() {
        return aab003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAB003
     *
     * @param aab003 the value for AK11.AAB003
     *
     * @mbg.generated
     */
    public void setAab003(String aab003) {
        this.aab003 = aab003 == null ? null : aab003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAB004
     *
     * @return the value of AK11.AAB004
     *
     * @mbg.generated
     */
    public String getAab004() {
        return aab004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAB004
     *
     * @param aab004 the value for AK11.AAB004
     *
     * @mbg.generated
     */
    public void setAab004(String aab004) {
        this.aab004 = aab004 == null ? null : aab004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR011
     *
     * @return the value of AK11.AAR011
     *
     * @mbg.generated
     */
    public String getAar011() {
        return aar011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR011
     *
     * @param aar011 the value for AK11.AAR011
     *
     * @mbg.generated
     */
    public void setAar011(String aar011) {
        this.aar011 = aar011 == null ? null : aar011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR012
     *
     * @return the value of AK11.AAR012
     *
     * @mbg.generated
     */
    public String getAar012() {
        return aar012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR012
     *
     * @param aar012 the value for AK11.AAR012
     *
     * @mbg.generated
     */
    public void setAar012(String aar012) {
        this.aar012 = aar012 == null ? null : aar012.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR013
     *
     * @return the value of AK11.AAR013
     *
     * @mbg.generated
     */
    public String getAar013() {
        return aar013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR013
     *
     * @param aar013 the value for AK11.AAR013
     *
     * @mbg.generated
     */
    public void setAar013(String aar013) {
        this.aar013 = aar013 == null ? null : aar013.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAP001
     *
     * @return the value of AK11.AAP001
     *
     * @mbg.generated
     */
    public String getAap001() {
        return aap001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAP001
     *
     * @param aap001 the value for AK11.AAP001
     *
     * @mbg.generated
     */
    public void setAap001(String aap001) {
        this.aap001 = aap001 == null ? null : aap001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAP004
     *
     * @return the value of AK11.AAP004
     *
     * @mbg.generated
     */
    public String getAap004() {
        return aap004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAP004
     *
     * @param aap004 the value for AK11.AAP004
     *
     * @mbg.generated
     */
    public void setAap004(String aap004) {
        this.aap004 = aap004 == null ? null : aap004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAK033
     *
     * @return the value of AK11.AAK033
     *
     * @mbg.generated
     */
    public String getAak033() {
        return aak033;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAK033
     *
     * @param aak033 the value for AK11.AAK033
     *
     * @mbg.generated
     */
    public void setAak033(String aak033) {
        this.aak033 = aak033 == null ? null : aak033.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAB005
     *
     * @return the value of AK11.AAB005
     *
     * @mbg.generated
     */
    public Long getAab005() {
        return aab005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAB005
     *
     * @param aab005 the value for AK11.AAB005
     *
     * @mbg.generated
     */
    public void setAab005(Long aab005) {
        this.aab005 = aab005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAF031
     *
     * @return the value of AK11.AAF031
     *
     * @mbg.generated
     */
    public String getAaf031() {
        return aaf031;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAF031
     *
     * @param aaf031 the value for AK11.AAF031
     *
     * @mbg.generated
     */
    public void setAaf031(String aaf031) {
        this.aaf031 = aaf031 == null ? null : aaf031.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAK036
     *
     * @return the value of AK11.AAK036
     *
     * @mbg.generated
     */
    public String getAak036() {
        return aak036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAK036
     *
     * @param aak036 the value for AK11.AAK036
     *
     * @mbg.generated
     */
    public void setAak036(String aak036) {
        this.aak036 = aak036 == null ? null : aak036.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAK037
     *
     * @return the value of AK11.AAK037
     *
     * @mbg.generated
     */
    public String getAak037() {
        return aak037;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAK037
     *
     * @param aak037 the value for AK11.AAK037
     *
     * @mbg.generated
     */
    public void setAak037(String aak037) {
        this.aak037 = aak037 == null ? null : aak037.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR001
     *
     * @return the value of AK11.AAR001
     *
     * @mbg.generated
     */
    public String getAar001() {
        return aar001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR001
     *
     * @param aar001 the value for AK11.AAR001
     *
     * @mbg.generated
     */
    public void setAar001(String aar001) {
        this.aar001 = aar001 == null ? null : aar001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR022
     *
     * @return the value of AK11.AAR022
     *
     * @mbg.generated
     */
    public String getAar022() {
        return aar022;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR022
     *
     * @param aar022 the value for AK11.AAR022
     *
     * @mbg.generated
     */
    public void setAar022(String aar022) {
        this.aar022 = aar022 == null ? null : aar022.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR023
     *
     * @return the value of AK11.AAR023
     *
     * @mbg.generated
     */
    public String getAar023() {
        return aar023;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR023
     *
     * @param aar023 the value for AK11.AAR023
     *
     * @mbg.generated
     */
    public void setAar023(String aar023) {
        this.aar023 = aar023 == null ? null : aar023.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR024
     *
     * @return the value of AK11.AAR024
     *
     * @mbg.generated
     */
    public Long getAar024() {
        return aar024;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR024
     *
     * @param aar024 the value for AK11.AAR024
     *
     * @mbg.generated
     */
    public void setAar024(Long aar024) {
        this.aar024 = aar024;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR025
     *
     * @return the value of AK11.AAR025
     *
     * @mbg.generated
     */
    public String getAar025() {
        return aar025;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR025
     *
     * @param aar025 the value for AK11.AAR025
     *
     * @mbg.generated
     */
    public void setAar025(String aar025) {
        this.aar025 = aar025 == null ? null : aar025.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.BAZ002
     *
     * @return the value of AK11.BAZ002
     *
     * @mbg.generated
     */
    public Long getBaz002() {
        return baz002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.BAZ002
     *
     * @param baz002 the value for AK11.BAZ002
     *
     * @mbg.generated
     */
    public void setBaz002(Long baz002) {
        this.baz002 = baz002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAR008
     *
     * @return the value of AK11.AAR008
     *
     * @mbg.generated
     */
    public String getAar008() {
        return aar008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAR008
     *
     * @param aar008 the value for AK11.AAR008
     *
     * @mbg.generated
     */
    public void setAar008(String aar008) {
        this.aar008 = aar008 == null ? null : aar008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.AAK111
     *
     * @return the value of AK11.AAK111
     *
     * @mbg.generated
     */
    public String getAak111() {
        return aak111;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.AAK111
     *
     * @param aak111 the value for AK11.AAK111
     *
     * @mbg.generated
     */
    public void setAak111(String aak111) {
        this.aak111 = aak111 == null ? null : aak111.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AK11.TIMESTAMP
     *
     * @return the value of AK11.TIMESTAMP
     *
     * @mbg.generated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AK11.TIMESTAMP
     *
     * @param timestamp the value for AK11.TIMESTAMP
     *
     * @mbg.generated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getAak666() {
        return aak666;
    }

    public void setAak666(String aak666) {
        this.aak666 = aak666;
    }

    public String getAak777() {
        return aak777;
    }

    public void setAak777(String aak777) {
        this.aak777 = aak777;
    }

    public String getAak888() {
        return aak888;
    }

    public void setAak888(String aak888) {
        this.aak888 = aak888;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AK11
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AK11DD other = (AK11DD) that;
        return (this.getAak110() == null ? other.getAak110() == null : this.getAak110().equals(other.getAak110()))
            && (this.getAap110() == null ? other.getAap110() == null : this.getAap110().equals(other.getAap110()))
            && (this.getAab002() == null ? other.getAab002() == null : this.getAab002().equals(other.getAab002()))
            && (this.getAak032() == null ? other.getAak032() == null : this.getAak032().equals(other.getAak032()))
            && (this.getAak031() == null ? other.getAak031() == null : this.getAak031().equals(other.getAak031()))
            && (this.getAak039() == null ? other.getAak039() == null : this.getAak039().equals(other.getAak039()))
            && (this.getAab003() == null ? other.getAab003() == null : this.getAab003().equals(other.getAab003()))
            && (this.getAab004() == null ? other.getAab004() == null : this.getAab004().equals(other.getAab004()))
            && (this.getAar011() == null ? other.getAar011() == null : this.getAar011().equals(other.getAar011()))
            && (this.getAar012() == null ? other.getAar012() == null : this.getAar012().equals(other.getAar012()))
            && (this.getAar013() == null ? other.getAar013() == null : this.getAar013().equals(other.getAar013()))
            && (this.getAap001() == null ? other.getAap001() == null : this.getAap001().equals(other.getAap001()))
            && (this.getAap004() == null ? other.getAap004() == null : this.getAap004().equals(other.getAap004()))
            && (this.getAak033() == null ? other.getAak033() == null : this.getAak033().equals(other.getAak033()))
            && (this.getAab005() == null ? other.getAab005() == null : this.getAab005().equals(other.getAab005()))
            && (this.getAaf031() == null ? other.getAaf031() == null : this.getAaf031().equals(other.getAaf031()))
            && (this.getAak036() == null ? other.getAak036() == null : this.getAak036().equals(other.getAak036()))
            && (this.getAak037() == null ? other.getAak037() == null : this.getAak037().equals(other.getAak037()))
            && (this.getAar001() == null ? other.getAar001() == null : this.getAar001().equals(other.getAar001()))
            && (this.getAar022() == null ? other.getAar022() == null : this.getAar022().equals(other.getAar022()))
            && (this.getAar023() == null ? other.getAar023() == null : this.getAar023().equals(other.getAar023()))
            && (this.getAar024() == null ? other.getAar024() == null : this.getAar024().equals(other.getAar024()))
            && (this.getAar025() == null ? other.getAar025() == null : this.getAar025().equals(other.getAar025()))
            && (this.getBaz002() == null ? other.getBaz002() == null : this.getBaz002().equals(other.getBaz002()))
            && (this.getAar008() == null ? other.getAar008() == null : this.getAar008().equals(other.getAar008()))
            && (this.getAak111() == null ? other.getAak111() == null : this.getAak111().equals(other.getAak111()))
            && (this.getTimestamp() == null ? other.getTimestamp() == null : this.getTimestamp().equals(other.getTimestamp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AK11
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAak110() == null) ? 0 : getAak110().hashCode());
        result = prime * result + ((getAap110() == null) ? 0 : getAap110().hashCode());
        result = prime * result + ((getAab002() == null) ? 0 : getAab002().hashCode());
        result = prime * result + ((getAak032() == null) ? 0 : getAak032().hashCode());
        result = prime * result + ((getAak031() == null) ? 0 : getAak031().hashCode());
        result = prime * result + ((getAak039() == null) ? 0 : getAak039().hashCode());
        result = prime * result + ((getAab003() == null) ? 0 : getAab003().hashCode());
        result = prime * result + ((getAab004() == null) ? 0 : getAab004().hashCode());
        result = prime * result + ((getAar011() == null) ? 0 : getAar011().hashCode());
        result = prime * result + ((getAar012() == null) ? 0 : getAar012().hashCode());
        result = prime * result + ((getAar013() == null) ? 0 : getAar013().hashCode());
        result = prime * result + ((getAap001() == null) ? 0 : getAap001().hashCode());
        result = prime * result + ((getAap004() == null) ? 0 : getAap004().hashCode());
        result = prime * result + ((getAak033() == null) ? 0 : getAak033().hashCode());
        result = prime * result + ((getAab005() == null) ? 0 : getAab005().hashCode());
        result = prime * result + ((getAaf031() == null) ? 0 : getAaf031().hashCode());
        result = prime * result + ((getAak036() == null) ? 0 : getAak036().hashCode());
        result = prime * result + ((getAak037() == null) ? 0 : getAak037().hashCode());
        result = prime * result + ((getAar001() == null) ? 0 : getAar001().hashCode());
        result = prime * result + ((getAar022() == null) ? 0 : getAar022().hashCode());
        result = prime * result + ((getAar023() == null) ? 0 : getAar023().hashCode());
        result = prime * result + ((getAar024() == null) ? 0 : getAar024().hashCode());
        result = prime * result + ((getAar025() == null) ? 0 : getAar025().hashCode());
        result = prime * result + ((getBaz002() == null) ? 0 : getBaz002().hashCode());
        result = prime * result + ((getAar008() == null) ? 0 : getAar008().hashCode());
        result = prime * result + ((getAak111() == null) ? 0 : getAak111().hashCode());
        result = prime * result + ((getTimestamp() == null) ? 0 : getTimestamp().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AK11
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aak110=").append(aak110);
        sb.append(", aap110=").append(aap110);
        sb.append(", aab002=").append(aab002);
        sb.append(", aak032=").append(aak032);
        sb.append(", aak031=").append(aak031);
        sb.append(", aak039=").append(aak039);
        sb.append(", aab003=").append(aab003);
        sb.append(", aab004=").append(aab004);
        sb.append(", aar011=").append(aar011);
        sb.append(", aar012=").append(aar012);
        sb.append(", aar013=").append(aar013);
        sb.append(", aap001=").append(aap001);
        sb.append(", aap004=").append(aap004);
        sb.append(", aak033=").append(aak033);
        sb.append(", aab005=").append(aab005);
        sb.append(", aaf031=").append(aaf031);
        sb.append(", aak036=").append(aak036);
        sb.append(", aak037=").append(aak037);
        sb.append(", aar001=").append(aar001);
        sb.append(", aar022=").append(aar022);
        sb.append(", aar023=").append(aar023);
        sb.append(", aar024=").append(aar024);
        sb.append(", aar025=").append(aar025);
        sb.append(", baz002=").append(baz002);
        sb.append(", aar008=").append(aar008);
        sb.append(", aak111=").append(aak111);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}