package com.sysh.entity;

import java.io.Serializable;

public class MeasureFieldDD implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MEASURE_FIELD.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MEASURE_FIELD.DATA_BASE
     *
     * @mbg.generated
     */
    private String dataBase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MEASURE_FIELD.DD_NAME
     *
     * @mbg.generated
     */
    private String ddName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MEASURE_FIELD.DD_VALUE
     *
     * @mbg.generated
     */
    private String ddValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_MEASURE_FIELD.TABLE_NAME
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MEASURE_FIELD.ID
     *
     * @return the value of TBL_MEASURE_FIELD.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MEASURE_FIELD.ID
     *
     * @param id the value for TBL_MEASURE_FIELD.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MEASURE_FIELD.DATA_BASE
     *
     * @return the value of TBL_MEASURE_FIELD.DATA_BASE
     *
     * @mbg.generated
     */
    public String getDataBase() {
        return dataBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MEASURE_FIELD.DATA_BASE
     *
     * @param dataBase the value for TBL_MEASURE_FIELD.DATA_BASE
     *
     * @mbg.generated
     */
    public void setDataBase(String dataBase) {
        this.dataBase = dataBase == null ? null : dataBase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MEASURE_FIELD.DD_NAME
     *
     * @return the value of TBL_MEASURE_FIELD.DD_NAME
     *
     * @mbg.generated
     */
    public String getDdName() {
        return ddName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MEASURE_FIELD.DD_NAME
     *
     * @param ddName the value for TBL_MEASURE_FIELD.DD_NAME
     *
     * @mbg.generated
     */
    public void setDdName(String ddName) {
        this.ddName = ddName == null ? null : ddName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MEASURE_FIELD.DD_VALUE
     *
     * @return the value of TBL_MEASURE_FIELD.DD_VALUE
     *
     * @mbg.generated
     */
    public String getDdValue() {
        return ddValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MEASURE_FIELD.DD_VALUE
     *
     * @param ddValue the value for TBL_MEASURE_FIELD.DD_VALUE
     *
     * @mbg.generated
     */
    public void setDdValue(String ddValue) {
        this.ddValue = ddValue == null ? null : ddValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_MEASURE_FIELD.TABLE_NAME
     *
     * @return the value of TBL_MEASURE_FIELD.TABLE_NAME
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_MEASURE_FIELD.TABLE_NAME
     *
     * @param tableName the value for TBL_MEASURE_FIELD.TABLE_NAME
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MeasureFieldDD other = (MeasureFieldDD) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDataBase() == null ? other.getDataBase() == null : this.getDataBase().equals(other.getDataBase()))
            && (this.getDdName() == null ? other.getDdName() == null : this.getDdName().equals(other.getDdName()))
            && (this.getDdValue() == null ? other.getDdValue() == null : this.getDdValue().equals(other.getDdValue()))
            && (this.getTableName() == null ? other.getTableName() == null : this.getTableName().equals(other.getTableName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDataBase() == null) ? 0 : getDataBase().hashCode());
        result = prime * result + ((getDdName() == null) ? 0 : getDdName().hashCode());
        result = prime * result + ((getDdValue() == null) ? 0 : getDdValue().hashCode());
        result = prime * result + ((getTableName() == null) ? 0 : getTableName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_MEASURE_FIELD
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dataBase=").append(dataBase);
        sb.append(", ddName=").append(ddName);
        sb.append(", ddValue=").append(ddValue);
        sb.append(", tableName=").append(tableName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}